/* Generated by Amaranth Yosys 0.40 (PyPI ver 0.40.0.0.post100, git sha1 a1bb0255d) */

(* top =  1  *)
(* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/top.py:34" *)
(* generator = "Amaranth" *)
module top(clk, rst, uo_out, ui_in);
  reg \$auto$verilog_backend.cc:2352:dump_module$1  = 0;
  wire \$1 ;
  wire \$2 ;
  reg [4:0] \$3 ;
  reg [4:0] \$4  = 5'h00;
  (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_ir.py:215" *)
  input clk;
  wire clk;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:18" *)
  wire [2:0] cmd;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:82" *)
  wire en;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:14" *)
  wire \en$30 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:23" *)
  wire [2:0] \en$31 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:14" *)
  wire \en$32 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:14" *)
  wire \en$33 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:14" *)
  wire \en$34 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:83" *)
  wire [4:0] in_ltor;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:86" *)
  wire [4:0] in_rtol;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:17" *)
  wire inc;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:26" *)
  wire [2:0] \inc$46 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:17" *)
  wire \inc$47 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:17" *)
  wire \inc$48 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:17" *)
  wire \inc$49 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:19" *)
  wire [2:0] is_at_turnover;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:13" *)
  wire \is_at_turnover$51 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:13" *)
  wire \is_at_turnover$52 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:13" *)
  wire \is_at_turnover$53 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:10" *)
  wire [4:0] left_in;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:10" *)
  wire [4:0] \left_in$23 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:10" *)
  wire [4:0] \left_in$25 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:10" *)
  wire [4:0] \left_in$27 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:8" *)
  wire [4:0] left_out;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:8" *)
  wire [4:0] \left_out$19 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:8" *)
  wire [4:0] \left_out$21 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:8" *)
  wire [4:0] \left_out$24 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:16" *)
  wire load_ring;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:25" *)
  wire \load_ring$41 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:16" *)
  wire \load_ring$42 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:16" *)
  wire \load_ring$43 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:16" *)
  wire \load_ring$44 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:15" *)
  wire load_start;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:24" *)
  wire \load_start$36 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:15" *)
  wire \load_start$37 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:15" *)
  wire \load_start$38 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:15" *)
  wire \load_start$39 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:84" *)
  wire [4:0] out_ltor;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:87" *)
  wire [4:0] out_rtol;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:30" *)
  wire plugboard_en;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:28" *)
  wire plugboard_wr_addr;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:29" *)
  wire plugboard_wr_data;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:21" *)
  wire ready;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:22" *)
  wire result_ready;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:7" *)
  wire [4:0] right_in;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:7" *)
  wire [4:0] \right_in$16 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:7" *)
  wire [4:0] \right_in$18 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:7" *)
  wire [4:0] \right_in$20 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/top.py:42" *)
  wire [4:0] right_out;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:11" *)
  wire [4:0] \right_out$26 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:11" *)
  wire [4:0] \right_out$28 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:11" *)
  wire [4:0] \right_out$29 ;
  (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_ir.py:215" *)
  input rst;
  wire rst;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/top.py:10" *)
  input [7:0] ui_in;
  wire [7:0] ui_in;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/top.py:11" *)
  output [5:0] uo_out;
  wire [5:0] uo_out;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:92" *)
  wire wr_addr_en;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:89" *)
  wire [4:0] wr_data;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:91" *)
  wire wr_data_en;
  assign \$1  = ui_in[7:5] == (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/top.py:63" *) 3'h4;
  assign \$2  = result_ready & (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/top.py:63" *) \$1 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/top.py:11" *)
  always @(posedge clk)
    \$4  <= \$3 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/top.py:39" *)
  \top.fsm  fsm (
    .clk(clk),
    .cmd(ui_in[7:5]),
    .en(\en$31 ),
    .inc(\inc$46 ),
    .is_at_turnover(is_at_turnover),
    .load_ring(load_ring),
    .load_start(load_start),
    .plugboard_en(en),
    .plugboard_wr_addr(wr_addr_en),
    .plugboard_wr_data(wr_data_en),
    .ready(ready),
    .result_ready(result_ready),
    .rst(rst)
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/top.py:40" *)
  \top.plugboard  plugboard (
    .in_ltor(in_ltor),
    .out_ltor(out_ltor),
    .out_rtol(right_in),
    .wr_data(ui_in[4:0]),
    .wr_data_en(wr_data_en)
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/top.py:35" *)
  \top.r0  r0 (
    .clk(clk),
    .en(\en$31 [0]),
    .inc(\inc$46 [0]),
    .is_at_turnover(\is_at_turnover$51 ),
    .left_in(\left_in$27 ),
    .left_out(\right_in$16 ),
    .load_ring(load_ring),
    .load_start(load_start),
    .right_in(right_in),
    .rst(rst),
    .swizz_l_minus_cnt_ring(in_ltor)
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/top.py:36" *)
  \top.r1  r1 (
    .clk(clk),
    .en(\en$31 [1]),
    .inc(\inc$46 [1]),
    .is_at_turnover(\is_at_turnover$52 ),
    .left_in(\left_in$25 ),
    .left_out(\right_in$18 ),
    .load_ring(load_ring),
    .load_start(load_start),
    .right_in(\right_in$16 ),
    .rst(rst),
    .swizz_l_minus_cnt_ring(\left_in$27 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/top.py:37" *)
  \top.r2  r2 (
    .clk(clk),
    .en(\en$31 [2]),
    .inc(\inc$46 [2]),
    .is_at_turnover(\is_at_turnover$53 ),
    .left_in(\left_in$23 ),
    .left_out(\right_in$20 ),
    .load_ring(load_ring),
    .load_start(load_start),
    .right_in(\right_in$18 ),
    .rst(rst),
    .swizz_l_minus_cnt_ring(\left_in$25 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/top.py:38" *)
  \top.ref  \ref  (
    .left_out(\left_in$23 ),
    .right_ptr(\right_in$20 )
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$3  = \$4 ;
    if (\$2 ) begin
      \$3  = out_ltor;
    end
    if (rst) begin
      \$3  = 5'h00;
    end
  end
  assign in_rtol = ui_in[4:0];
  assign right_out = in_ltor;
  assign plugboard_en = en;
  assign wr_data = ui_in[4:0];
  assign plugboard_wr_data = wr_data_en;
  assign plugboard_wr_addr = wr_addr_en;
  assign out_rtol = right_in;
  assign left_out = \right_in$16 ;
  assign \left_out$19  = \right_in$18 ;
  assign \left_out$21  = \right_in$20 ;
  assign left_in = 5'h00;
  assign \left_out$24  = \left_in$23 ;
  assign \right_out$26  = \left_in$25 ;
  assign \right_out$28  = \left_in$27 ;
  assign \right_out$29  = in_ltor;
  assign \en$30  = \en$31 [0];
  assign \en$32  = \en$31 [1];
  assign \en$33  = \en$31 [2];
  assign \en$34  = 1'h0;
  assign \load_start$36  = load_start;
  assign \load_start$37  = load_start;
  assign \load_start$38  = load_start;
  assign \load_start$39  = 1'h0;
  assign \load_ring$41  = load_ring;
  assign \load_ring$42  = load_ring;
  assign \load_ring$43  = load_ring;
  assign \load_ring$44  = 1'h0;
  assign inc = \inc$46 [0];
  assign \inc$47  = \inc$46 [1];
  assign \inc$48  = \inc$46 [2];
  assign \inc$49  = 1'h0;
  assign cmd = ui_in[7:5];
  assign uo_out = { ready, \$4  };
  assign is_at_turnover[2] = \is_at_turnover$53 ;
  assign is_at_turnover[1] = \is_at_turnover$52 ;
  assign is_at_turnover[0] = \is_at_turnover$51 ;
endmodule

(* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:37" *)
(* generator = "Amaranth" *)
module \top.fsm (clk, rst, is_at_turnover, en, ready, load_start, load_ring, plugboard_en, plugboard_wr_addr, plugboard_wr_data, result_ready, inc, cmd);
  reg \$auto$verilog_backend.cc:2352:dump_module$2  = 0;
  wire \$1 ;
  wire \$10 ;
  wire \$11 ;
  wire [2:0] \$12 ;
  wire [2:0] \$13 ;
  wire \$14 ;
  wire \$15 ;
  wire \$16 ;
  reg [1:0] \$17 ;
  reg [3:0] \$18 ;
  reg [2:0] \$19 ;
  wire \$2 ;
  reg \$20 ;
  wire \$3 ;
  wire \$4 ;
  wire \$5 ;
  wire \$6 ;
  wire \$7 ;
  wire \$8 ;
  wire \$9 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:39" *)
  reg [1:0] active;
  (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_ir.py:215" *)
  input clk;
  wire clk;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:18" *)
  input [2:0] cmd;
  wire [2:0] cmd;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:38" *)
  reg [1:0] cnt = 2'h0;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:41" *)
  reg double_step = 1'h0;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:23" *)
  output [2:0] en;
  reg [2:0] en;
  (* enum_base_type = "fsmState" *)
  (* enum_value_0000 = "Initial/0" *)
  (* enum_value_0001 = "Get command/1" *)
  (* enum_value_0010 = "Load start/2" *)
  (* enum_value_0011 = "Load ring/3" *)
  (* enum_value_0100 = "Load plug addr/4" *)
  (* enum_value_0101 = "Load plug data/5" *)
  (* enum_value_0110 = "Inc Rotor 0/6" *)
  (* enum_value_0111 = "Inc Rotor 1/7" *)
  (* enum_value_1000 = "Delay/8" *)
  (* enum_value_1001 = "Check Rotor 1 Turnover/9" *)
  (* enum_value_1010 = "Inc Rotor 2/10" *)
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:66" *)
  reg [3:0] fsm_state = 4'h0;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:40" *)
  output [2:0] inc;
  reg [2:0] inc = 3'h0;
  (* init = 3'h0 *)
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:40" *)
  wire [2:0] \inc$1 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:19" *)
  input [2:0] is_at_turnover;
  wire [2:0] is_at_turnover;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:25" *)
  output load_ring;
  reg load_ring;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:24" *)
  output load_start;
  reg load_start;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:30" *)
  output plugboard_en;
  reg plugboard_en;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:28" *)
  output plugboard_wr_addr;
  reg plugboard_wr_addr;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:29" *)
  output plugboard_wr_data;
  reg plugboard_wr_data;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:21" *)
  output ready;
  reg ready;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:22" *)
  output result_ready;
  reg result_ready;
  (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_ir.py:215" *)
  input rst;
  wire rst;
  assign \$1  = ! (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) fsm_state;
  assign \$2  = fsm_state == (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) 1'h1;
  assign \$3  = fsm_state == (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) 2'h2;
  assign \$4  = fsm_state == (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) 2'h3;
  assign \$5  = fsm_state == (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) 3'h4;
  assign \$6  = fsm_state == (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) 3'h5;
  assign \$7  = fsm_state == (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) 3'h6;
  assign \$8  = fsm_state == (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) 3'h7;
  assign \$9  = fsm_state == (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) 4'h8;
  assign \$10  = fsm_state == (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) 4'h9;
  assign \$11  = fsm_state == (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) 4'ha;
  assign \$12  = cnt + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:90" *) 1'h1;
  assign \$13  = cnt + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:93" *) 1'h1;
  assign \$14  = cnt == (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:119" *) 2'h3;
  assign \$15  = cnt == (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:130" *) 2'h3;
  assign \$16  = is_at_turnover[0] | (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:141" *) double_step;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:38" *)
  always @(posedge clk)
    cnt <= \$17 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:66" *)
  always @(posedge clk)
    fsm_state <= \$18 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:40" *)
  always @(posedge clk)
    inc <= \$19 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:41" *)
  always @(posedge clk)
    double_step <= \$20 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    (* full_case = 32'd1 *)
    casez (active)
      2'h1:
          en = 3'h1;
      2'h2:
          en = 3'h2;
      2'h3:
          en = 3'h4;
      default:
          en = 3'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    ready = 1'h0;
    casez (fsm_state)
      4'h0:
          /* empty */;
      4'h1:
          ready = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    load_start = 1'h0;
    casez (fsm_state)
      4'h0:
          /* empty */;
      4'h1:
          load_start = 1'h0;
      4'h4:
          /* empty */;
      4'h5:
          /* empty */;
      4'h2:
          load_start = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    load_ring = 1'h0;
    casez (fsm_state)
      4'h0:
          /* empty */;
      4'h1:
          load_ring = 1'h0;
      4'h4:
          /* empty */;
      4'h5:
          /* empty */;
      4'h2:
          /* empty */;
      4'h3:
          load_ring = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    plugboard_en = 1'h0;
    casez (fsm_state)
      4'h0:
          /* empty */;
      4'h1:
          plugboard_en = 1'h1;
      4'h4:
          /* empty */;
      4'h5:
          /* empty */;
      4'h2:
          /* empty */;
      4'h3:
          /* empty */;
      4'h6:
          plugboard_en = 1'h1;
      4'h7:
          plugboard_en = 1'h1;
      4'h9:
          plugboard_en = 1'h1;
      4'ha:
          plugboard_en = 1'h1;
      4'h8:
          plugboard_en = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    plugboard_wr_addr = 1'h0;
    casez (fsm_state)
      4'h0:
          /* empty */;
      4'h1:
          /* empty */;
      4'h4:
          plugboard_wr_addr = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    plugboard_wr_data = 1'h0;
    casez (fsm_state)
      4'h0:
          /* empty */;
      4'h1:
          /* empty */;
      4'h4:
          /* empty */;
      4'h5:
          plugboard_wr_data = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    active = 2'h0;
    casez (fsm_state)
      4'h0:
          /* empty */;
      4'h1:
          /* empty */;
      4'h4:
          /* empty */;
      4'h5:
          /* empty */;
      4'h2:
          active = cnt;
      4'h3:
          active = cnt;
      4'h6:
          active = cnt;
      4'h7:
          active = cnt;
      4'h9:
          /* empty */;
      4'ha:
          active = cnt;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    result_ready = 1'h0;
    casez (fsm_state)
      4'h0:
          /* empty */;
      4'h1:
          /* empty */;
      4'h4:
          /* empty */;
      4'h5:
          /* empty */;
      4'h2:
          /* empty */;
      4'h3:
          /* empty */;
      4'h6:
          /* empty */;
      4'h7:
          /* empty */;
      4'h9:
          /* empty */;
      4'ha:
          /* empty */;
      4'h8:
          result_ready = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    \$17  = cnt;
    casez (fsm_state)
      4'h0:
          \$17  = 2'h0;
      4'h1:
        begin
          \$17  = 2'h0;
          casez (cmd)
            3'h3:
                /* empty */;
            3'h1:
                \$17  = \$12 [1:0];
            3'h2:
                \$17  = \$13 [1:0];
            3'h5:
                /* empty */;
            3'h6:
                /* empty */;
            3'h4:
                \$17  = 2'h1;
          endcase
        end
      4'h4:
          /* empty */;
      4'h5:
          /* empty */;
      4'h2:
          if (\$14 ) begin
            \$17  = 2'h0;
          end
      4'h3:
          if (\$15 ) begin
            \$17  = 2'h0;
          end
      4'h6:
          if (\$16 ) begin
            \$17  = 2'h2;
          end
      4'h7:
          \$17  = 2'h2;
      4'h9:
          if (is_at_turnover[1]) begin
          end else if (double_step) begin
            \$17  = 2'h3;
          end
      4'ha:
          \$17  = 2'h0;
    endcase
    if (rst) begin
      \$17  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    \$18  = fsm_state;
    casez (fsm_state)
      4'h0:
          \$18  = 4'h1;
      4'h1:
          (* full_case = 32'd1 *)
          casez (cmd)
            3'h3:
                \$18  = 4'h0;
            3'h1:
                \$18  = 4'h2;
            3'h2:
                \$18  = 4'h3;
            3'h5:
                \$18  = 4'h4;
            3'h6:
                \$18  = 4'h5;
            3'h4:
                \$18  = 4'h6;
            default:
                \$18  = 4'h1;
          endcase
      4'h4:
          \$18  = 4'h1;
      4'h5:
          \$18  = 4'h1;
      4'h2:
          (* full_case = 32'd1 *)
          if (\$14 ) begin
            \$18  = 4'h1;
          end else begin
            \$18  = 4'h1;
          end
      4'h3:
          \$18  = 4'h1;
      4'h6:
          (* full_case = 32'd1 *)
          if (\$16 ) begin
            \$18  = 4'h7;
          end else begin
            \$18  = 4'h8;
          end
      4'h7:
          \$18  = 4'h9;
      4'h9:
          (* full_case = 32'd1 *)
          if (is_at_turnover[1]) begin
            \$18  = 4'h8;
          end else if (double_step) begin
            \$18  = 4'ha;
          end else begin
            \$18  = 4'h8;
          end
      4'ha:
          \$18  = 4'h8;
      4'h8:
          \$18  = 4'h1;
    endcase
    if (rst) begin
      \$18  = 4'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    \$19  = inc;
    casez (fsm_state)
      4'h0:
          /* empty */;
      4'h1:
        begin
          \$19  = 3'h0;
          casez (cmd)
            3'h3:
                /* empty */;
            3'h1:
                /* empty */;
            3'h2:
                /* empty */;
            3'h5:
                /* empty */;
            3'h6:
                /* empty */;
            3'h4:
                \$19 [0] = 1'h1;
          endcase
        end
      4'h4:
          /* empty */;
      4'h5:
          /* empty */;
      4'h2:
          /* empty */;
      4'h3:
          /* empty */;
      4'h6:
          if (\$16 ) begin
            \$19 [0] = 1'h0;
            \$19 [1] = 1'h1;
          end
      4'h7:
          \$19 [1] = 1'h0;
      4'h9:
        begin
          \$19 [0] = 1'h0;
          \$19 [1] = 1'h0;
          if (is_at_turnover[1]) begin
          end else if (double_step) begin
            \$19 [2] = 1'h1;
          end
        end
      4'ha:
        begin
          \$19 [0] = 1'h0;
          \$19 [1] = 1'h0;
          \$19 [2] = 1'h0;
        end
    endcase
    if (rst) begin
      \$19  = 3'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    \$20  = double_step;
    casez (fsm_state)
      4'h0:
          /* empty */;
      4'h1:
          /* empty */;
      4'h4:
          /* empty */;
      4'h5:
          /* empty */;
      4'h2:
          /* empty */;
      4'h3:
          /* empty */;
      4'h6:
          /* empty */;
      4'h7:
          /* empty */;
      4'h9:
          if (is_at_turnover[1]) begin
            \$20  = 1'h1;
          end
      4'ha:
          \$20  = 1'h0;
    endcase
    if (rst) begin
      \$20  = 1'h0;
    end
  end
  assign \inc$1  = inc;
endmodule

(* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:98" *)
(* generator = "Amaranth" *)
module \top.plugboard (in_ltor, out_rtol, out_ltor, wr_data_en, wr_data);
  reg \$auto$verilog_backend.cc:2352:dump_module$3  = 0;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:101" *)
  wire [4:0] \$signal ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:120" *)
  wire \$signal$107 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:120" *)
  wire \$signal$118 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:101" *)
  wire [4:0] \$signal$12 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:120" *)
  wire \$signal$129 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:120" *)
  wire \$signal$140 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:120" *)
  wire \$signal$151 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:101" *)
  wire [4:0] \$signal$18 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:101" *)
  wire [4:0] \$signal$24 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:101" *)
  wire [4:0] \$signal$30 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:101" *)
  wire [4:0] \$signal$36 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:101" *)
  wire [4:0] \$signal$42 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:101" *)
  wire [4:0] \$signal$48 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:101" *)
  wire [4:0] \$signal$54 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:101" *)
  wire [4:0] \$signal$6 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:120" *)
  wire \$signal$63 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:120" *)
  wire \$signal$74 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:120" *)
  wire \$signal$85 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:120" *)
  wire \$signal$96 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire d;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$101 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$103 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$105 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$108 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$110 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$112 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$114 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$116 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$119 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$121 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$123 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$125 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$127 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$130 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$132 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$134 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$136 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$138 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$141 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$143 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$145 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$147 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$149 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$152 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$154 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$156 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$158 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$64 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$66 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$68 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$70 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$72 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$75 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$77 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$79 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$81 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$83 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$86 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$88 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$90 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$92 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$94 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$97 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:46" *)
  wire \d$99 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  reg en;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$100 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$102 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$104 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  reg \en$106 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$109 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$111 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$113 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$115 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  reg \en$117 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$120 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$122 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$124 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$126 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  reg \en$128 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$131 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$133 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$135 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$137 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  reg \en$139 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$142 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$144 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$146 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$148 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  reg \en$150 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$153 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$155 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$157 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$159 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$65 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$67 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$69 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$71 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  reg \en$73 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$76 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$78 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$80 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$82 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  reg \en$84 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$87 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$89 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$91 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$93 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  reg \en$95 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:48" *)
  wire \en$98 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:83" *)
  input [4:0] in_ltor;
  wire [4:0] in_ltor;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:86" *)
  wire [4:0] in_rtol;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:84" *)
  output [4:0] out_ltor;
  reg [4:0] out_ltor;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:87" *)
  output [4:0] out_rtol;
  reg [4:0] out_rtol;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire q;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$10 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$11 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$13 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$14 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$15 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$16 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$17 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$19 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$2 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$20 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$21 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$22 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$23 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$25 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$26 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$27 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$28 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$29 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$3 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$31 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$32 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$33 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$34 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$35 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$37 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$38 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$39 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$4 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$40 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$41 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$43 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$44 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$45 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$46 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$47 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$49 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$5 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$50 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$51 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$52 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$53 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$55 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$56 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$57 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$58 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$59 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$7 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$8 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:47" *)
  wire \q$9 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:86" *)
  input [4:0] wr_data;
  wire [4:0] wr_data;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:91" *)
  input wr_data_en;
  wire wr_data_en;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_0_0 (
    .clk(en),
    .d(wr_data[0]),
    .q(q)
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_0_1 (
    .clk(en),
    .d(wr_data[1]),
    .q(\q$2 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_0_2 (
    .clk(en),
    .d(wr_data[2]),
    .q(\q$3 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_0_3 (
    .clk(en),
    .d(wr_data[3]),
    .q(\q$4 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_0_4 (
    .clk(en),
    .d(wr_data[4]),
    .q(\q$5 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_1_0 (
    .clk(\en$73 ),
    .d(wr_data[0]),
    .q(\q$7 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_1_1 (
    .clk(\en$73 ),
    .d(wr_data[1]),
    .q(\q$8 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_1_2 (
    .clk(\en$73 ),
    .d(wr_data[2]),
    .q(\q$9 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_1_3 (
    .clk(\en$73 ),
    .d(wr_data[3]),
    .q(\q$10 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_1_4 (
    .clk(\en$73 ),
    .d(wr_data[4]),
    .q(\q$11 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_2_0 (
    .clk(\en$84 ),
    .d(wr_data[0]),
    .q(\q$13 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_2_1 (
    .clk(\en$84 ),
    .d(wr_data[1]),
    .q(\q$14 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_2_2 (
    .clk(\en$84 ),
    .d(wr_data[2]),
    .q(\q$15 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_2_3 (
    .clk(\en$84 ),
    .d(wr_data[3]),
    .q(\q$16 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_2_4 (
    .clk(\en$84 ),
    .d(wr_data[4]),
    .q(\q$17 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_3_0 (
    .clk(\en$95 ),
    .d(wr_data[0]),
    .q(\q$19 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_3_1 (
    .clk(\en$95 ),
    .d(wr_data[1]),
    .q(\q$20 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_3_2 (
    .clk(\en$95 ),
    .d(wr_data[2]),
    .q(\q$21 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_3_3 (
    .clk(\en$95 ),
    .d(wr_data[3]),
    .q(\q$22 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_3_4 (
    .clk(\en$95 ),
    .d(wr_data[4]),
    .q(\q$23 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_4_0 (
    .clk(\en$106 ),
    .d(wr_data[0]),
    .q(\q$25 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_4_1 (
    .clk(\en$106 ),
    .d(wr_data[1]),
    .q(\q$26 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_4_2 (
    .clk(\en$106 ),
    .d(wr_data[2]),
    .q(\q$27 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_4_3 (
    .clk(\en$106 ),
    .d(wr_data[3]),
    .q(\q$28 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_4_4 (
    .clk(\en$106 ),
    .d(wr_data[4]),
    .q(\q$29 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_5_0 (
    .clk(\en$117 ),
    .d(wr_data[0]),
    .q(\q$31 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_5_1 (
    .clk(\en$117 ),
    .d(wr_data[1]),
    .q(\q$32 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_5_2 (
    .clk(\en$117 ),
    .d(wr_data[2]),
    .q(\q$33 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_5_3 (
    .clk(\en$117 ),
    .d(wr_data[3]),
    .q(\q$34 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_5_4 (
    .clk(\en$117 ),
    .d(wr_data[4]),
    .q(\q$35 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_6_0 (
    .clk(\en$128 ),
    .d(wr_data[0]),
    .q(\q$37 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_6_1 (
    .clk(\en$128 ),
    .d(wr_data[1]),
    .q(\q$38 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_6_2 (
    .clk(\en$128 ),
    .d(wr_data[2]),
    .q(\q$39 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_6_3 (
    .clk(\en$128 ),
    .d(wr_data[3]),
    .q(\q$40 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_6_4 (
    .clk(\en$128 ),
    .d(wr_data[4]),
    .q(\q$41 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_7_0 (
    .clk(\en$139 ),
    .d(wr_data[0]),
    .q(\q$43 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_7_1 (
    .clk(\en$139 ),
    .d(wr_data[1]),
    .q(\q$44 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_7_2 (
    .clk(\en$139 ),
    .d(wr_data[2]),
    .q(\q$45 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_7_3 (
    .clk(\en$139 ),
    .d(wr_data[3]),
    .q(\q$46 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_7_4 (
    .clk(\en$139 ),
    .d(wr_data[4]),
    .q(\q$47 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_8_0 (
    .clk(\en$150 ),
    .d(wr_data[0]),
    .q(\q$49 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_8_1 (
    .clk(\en$150 ),
    .d(wr_data[1]),
    .q(\q$50 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_8_2 (
    .clk(\en$150 ),
    .d(wr_data[2]),
    .q(\q$51 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_8_3 (
    .clk(\en$150 ),
    .d(wr_data[3]),
    .q(\q$52 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_8_4 (
    .clk(\en$150 ),
    .d(wr_data[4]),
    .q(\q$53 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_9_0 (
    .clk(1'h0),
    .d(1'h0),
    .q(\q$55 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_9_1 (
    .clk(1'h0),
    .d(1'h0),
    .q(\q$56 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_9_2 (
    .clk(1'h0),
    .d(1'h0),
    .q(\q$57 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_9_3 (
    .clk(1'h0),
    .d(1'h0),
    .q(\q$58 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/plugboard3.py:52" *)
  d_latch bits_9_4 (
    .clk(1'h0),
    .d(1'h0),
    .q(\q$59 )
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$3 ) begin end
    out_rtol = 5'h00;
    casez (wr_data)
      5'h00:
          out_rtol = \$signal ;
      5'h01:
          out_rtol = \$signal$6 ;
      5'h02:
          out_rtol = \$signal$12 ;
      5'h03:
          out_rtol = \$signal$18 ;
      5'h04:
          out_rtol = \$signal$24 ;
      5'h05:
          out_rtol = \$signal$30 ;
      5'h06:
          out_rtol = \$signal$36 ;
      5'h07:
          out_rtol = \$signal$42 ;
      5'h08:
          out_rtol = \$signal$48 ;
      5'h09:
          out_rtol = \$signal$54 ;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$3 ) begin end
    en = 1'h0;
    if (wr_data_en) begin
      casez (wr_data)
        5'h00:
            en = 1'h1;
      endcase
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$3 ) begin end
    \en$73  = 1'h0;
    if (wr_data_en) begin
      casez (wr_data)
        5'h00:
            /* empty */;
        5'h01:
            \en$73  = 1'h1;
      endcase
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$3 ) begin end
    \en$84  = 1'h0;
    if (wr_data_en) begin
      casez (wr_data)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            \en$84  = 1'h1;
      endcase
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$3 ) begin end
    \en$95  = 1'h0;
    if (wr_data_en) begin
      casez (wr_data)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            \en$95  = 1'h1;
      endcase
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$3 ) begin end
    \en$106  = 1'h0;
    if (wr_data_en) begin
      casez (wr_data)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            \en$106  = 1'h1;
      endcase
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$3 ) begin end
    \en$117  = 1'h0;
    if (wr_data_en) begin
      casez (wr_data)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            \en$117  = 1'h1;
      endcase
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$3 ) begin end
    \en$128  = 1'h0;
    if (wr_data_en) begin
      casez (wr_data)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            /* empty */;
        5'h06:
            \en$128  = 1'h1;
      endcase
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$3 ) begin end
    out_ltor = 5'h00;
    casez (in_ltor)
      5'h00:
          out_ltor = \$signal ;
      5'h01:
          out_ltor = \$signal$6 ;
      5'h02:
          out_ltor = \$signal$12 ;
      5'h03:
          out_ltor = \$signal$18 ;
      5'h04:
          out_ltor = \$signal$24 ;
      5'h05:
          out_ltor = \$signal$30 ;
      5'h06:
          out_ltor = \$signal$36 ;
      5'h07:
          out_ltor = \$signal$42 ;
      5'h08:
          out_ltor = \$signal$48 ;
      5'h09:
          out_ltor = \$signal$54 ;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$3 ) begin end
    \en$139  = 1'h0;
    if (wr_data_en) begin
      casez (wr_data)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            /* empty */;
        5'h06:
            /* empty */;
        5'h07:
            \en$139  = 1'h1;
      endcase
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$3 ) begin end
    \en$150  = 1'h0;
    if (wr_data_en) begin
      casez (wr_data)
        5'h00:
            /* empty */;
        5'h01:
            /* empty */;
        5'h02:
            /* empty */;
        5'h03:
            /* empty */;
        5'h04:
            /* empty */;
        5'h05:
            /* empty */;
        5'h06:
            /* empty */;
        5'h07:
            /* empty */;
        5'h08:
            \en$150  = 1'h1;
      endcase
    end
  end
  assign d = wr_data[0];
  assign \$signal$63  = en;
  assign \d$64  = wr_data[1];
  assign \en$65  = en;
  assign \d$66  = wr_data[2];
  assign \en$67  = en;
  assign \d$68  = wr_data[3];
  assign \en$69  = en;
  assign \d$70  = wr_data[4];
  assign \en$71  = en;
  assign \d$72  = wr_data[0];
  assign \$signal$74  = \en$73 ;
  assign \d$75  = wr_data[1];
  assign \en$76  = \en$73 ;
  assign \d$77  = wr_data[2];
  assign \en$78  = \en$73 ;
  assign \d$79  = wr_data[3];
  assign \en$80  = \en$73 ;
  assign \d$81  = wr_data[4];
  assign \en$82  = \en$73 ;
  assign \d$83  = wr_data[0];
  assign \$signal$85  = \en$84 ;
  assign \d$86  = wr_data[1];
  assign \en$87  = \en$84 ;
  assign \d$88  = wr_data[2];
  assign \en$89  = \en$84 ;
  assign \d$90  = wr_data[3];
  assign \en$91  = \en$84 ;
  assign \d$92  = wr_data[4];
  assign \en$93  = \en$84 ;
  assign \d$94  = wr_data[0];
  assign \$signal$96  = \en$95 ;
  assign \d$97  = wr_data[1];
  assign \en$98  = \en$95 ;
  assign \d$99  = wr_data[2];
  assign \en$100  = \en$95 ;
  assign \d$101  = wr_data[3];
  assign \en$102  = \en$95 ;
  assign \d$103  = wr_data[4];
  assign \en$104  = \en$95 ;
  assign \d$105  = wr_data[0];
  assign \$signal$107  = \en$106 ;
  assign \d$108  = wr_data[1];
  assign \en$109  = \en$106 ;
  assign \d$110  = wr_data[2];
  assign \en$111  = \en$106 ;
  assign \d$112  = wr_data[3];
  assign \en$113  = \en$106 ;
  assign \d$114  = wr_data[4];
  assign \en$115  = \en$106 ;
  assign \d$116  = wr_data[0];
  assign \$signal$118  = \en$117 ;
  assign \d$119  = wr_data[1];
  assign \en$120  = \en$117 ;
  assign \d$121  = wr_data[2];
  assign \en$122  = \en$117 ;
  assign \d$123  = wr_data[3];
  assign \en$124  = \en$117 ;
  assign \d$125  = wr_data[4];
  assign \en$126  = \en$117 ;
  assign \d$127  = wr_data[0];
  assign \$signal$129  = \en$128 ;
  assign \d$130  = wr_data[1];
  assign \en$131  = \en$128 ;
  assign \d$132  = wr_data[2];
  assign \en$133  = \en$128 ;
  assign \d$134  = wr_data[3];
  assign \en$135  = \en$128 ;
  assign \d$136  = wr_data[4];
  assign \en$137  = \en$128 ;
  assign \d$138  = wr_data[0];
  assign \$signal$140  = \en$139 ;
  assign \d$141  = wr_data[1];
  assign \en$142  = \en$139 ;
  assign \d$143  = wr_data[2];
  assign \en$144  = \en$139 ;
  assign \d$145  = wr_data[3];
  assign \en$146  = \en$139 ;
  assign \d$147  = wr_data[4];
  assign \en$148  = \en$139 ;
  assign \d$149  = wr_data[0];
  assign \$signal$151  = \en$150 ;
  assign \d$152  = wr_data[1];
  assign \en$153  = \en$150 ;
  assign \d$154  = wr_data[2];
  assign \en$155  = \en$150 ;
  assign \d$156  = wr_data[3];
  assign \en$157  = \en$150 ;
  assign \d$158  = wr_data[4];
  assign \en$159  = \en$150 ;
  assign in_rtol = wr_data;
  assign \$signal$54 [4] = \q$59 ;
  assign \$signal$54 [3] = \q$58 ;
  assign \$signal$54 [2] = \q$57 ;
  assign \$signal$54 [1] = \q$56 ;
  assign \$signal$54 [0] = \q$55 ;
  assign \$signal$48 [4] = \q$53 ;
  assign \$signal$48 [3] = \q$52 ;
  assign \$signal$48 [2] = \q$51 ;
  assign \$signal$48 [1] = \q$50 ;
  assign \$signal$48 [0] = \q$49 ;
  assign \$signal$42 [4] = \q$47 ;
  assign \$signal$42 [3] = \q$46 ;
  assign \$signal$42 [2] = \q$45 ;
  assign \$signal$42 [1] = \q$44 ;
  assign \$signal$42 [0] = \q$43 ;
  assign \$signal$36 [4] = \q$41 ;
  assign \$signal$36 [3] = \q$40 ;
  assign \$signal$36 [2] = \q$39 ;
  assign \$signal$36 [1] = \q$38 ;
  assign \$signal$36 [0] = \q$37 ;
  assign \$signal$30 [4] = \q$35 ;
  assign \$signal$30 [3] = \q$34 ;
  assign \$signal$30 [2] = \q$33 ;
  assign \$signal$30 [1] = \q$32 ;
  assign \$signal$30 [0] = \q$31 ;
  assign \$signal$24 [4] = \q$29 ;
  assign \$signal$24 [3] = \q$28 ;
  assign \$signal$24 [2] = \q$27 ;
  assign \$signal$24 [1] = \q$26 ;
  assign \$signal$24 [0] = \q$25 ;
  assign \$signal$18 [4] = \q$23 ;
  assign \$signal$18 [3] = \q$22 ;
  assign \$signal$18 [2] = \q$21 ;
  assign \$signal$18 [1] = \q$20 ;
  assign \$signal$18 [0] = \q$19 ;
  assign \$signal$12 [4] = \q$17 ;
  assign \$signal$12 [3] = \q$16 ;
  assign \$signal$12 [2] = \q$15 ;
  assign \$signal$12 [1] = \q$14 ;
  assign \$signal$12 [0] = \q$13 ;
  assign \$signal$6 [4] = \q$11 ;
  assign \$signal$6 [3] = \q$10 ;
  assign \$signal$6 [2] = \q$9 ;
  assign \$signal$6 [1] = \q$8 ;
  assign \$signal$6 [0] = \q$7 ;
  assign \$signal [4] = \q$5 ;
  assign \$signal [3] = \q$4 ;
  assign \$signal [2] = \q$3 ;
  assign \$signal [1] = \q$2 ;
  assign \$signal [0] = q;
endmodule

(* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:31" *)
(* generator = "Amaranth" *)
module \top.r0 (rst, is_at_turnover, left_out, swizz_l_minus_cnt_ring, left_in, right_in, en, load_start, load_ring, inc, clk);
  reg \$auto$verilog_backend.cc:2352:dump_module$4  = 0;
  wire \$1 ;
  wire \$10 ;
  wire \$11 ;
  wire \$12 ;
  wire [6:0] \$13 ;
  reg [4:0] \$14 ;
  wire [6:0] \$15 ;
  wire [6:0] \$16 ;
  wire \$17 ;
  wire [5:0] \$18 ;
  reg [4:0] \$19 ;
  wire [5:0] \$2 ;
  reg [4:0] \$20 ;
  wire [6:0] \$3 ;
  wire [5:0] \$4 ;
  wire \$5 ;
  wire \$6 ;
  wire [6:0] \$7 ;
  wire [6:0] \$8 ;
  wire [6:0] \$9 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:80" *)
  wire [5:0] a_ext;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:80" *)
  wire [5:0] \a_ext$23 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:81" *)
  wire [5:0] b_ext;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:81" *)
  wire [5:0] \b_ext$24 ;
  (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_ir.py:215" *)
  input clk;
  wire clk;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:21" *)
  reg [4:0] cnt = 5'h00;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:33" *)
  reg [4:0] cnt_ring_combined;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:82" *)
  wire [5:0] diff_plus_26;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:82" *)
  wire [5:0] \diff_plus_26$26 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:14" *)
  input en;
  wire en;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:17" *)
  input inc;
  wire inc;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:13" *)
  output is_at_turnover;
  wire is_at_turnover;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:10" *)
  input [4:0] left_in;
  wire [4:0] left_in;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:8" *)
  output [4:0] left_out;
  wire [4:0] left_out;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:27" *)
  wire [4:0] left_ptr;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:16" *)
  input load_ring;
  wire load_ring;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:15" *)
  input load_start;
  wire load_start;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:7" *)
  input [4:0] right_in;
  wire [4:0] right_in;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:11" *)
  wire [4:0] right_out;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:22" *)
  wire [4:0] right_ptr;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:24" *)
  reg [4:0] ring_setting = 5'h00;
  (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_ir.py:215" *)
  input rst;
  wire rst;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:23" *)
  reg [4:0] rtol_swizzle;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:68" *)
  wire [5:0] s;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:79" *)
  wire [5:0] \s$12 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:68" *)
  wire [5:0] \s$18 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:79" *)
  wire [5:0] \s$25 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:70" *)
  wire s_ge_26;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:70" *)
  wire \s_ge_26$20 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:69" *)
  wire [5:0] s_m_26;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:69" *)
  wire [5:0] \s_m_26$21 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:11" *)
  output [4:0] swizz_l_minus_cnt_ring;
  wire [4:0] swizz_l_minus_cnt_ring;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:119" *)
  wire [4:0] swizz_minus_cnt_ring;
  assign \$1  = ring_setting > (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:34" *) cnt;
  assign \$2  = ring_setting - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:35" *) cnt;
  assign \$3  = $signed(6'h1a) - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:35" *) $signed(\$2 );
  assign \$4  = cnt - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:37" *) ring_setting;
  assign is_at_turnover = cnt == (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:61" *) 5'h10;
  assign s = right_in + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:72" *) cnt_ring_combined;
  assign \$6  = s[4:0] >= (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:73" *) 5'h1a;
  assign s_ge_26 = \$5  | (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:73" *) \$6 ;
  assign \$7  = s - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:74" *) 5'h1a;
  assign right_ptr = s_ge_26 ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:75" *) \$7 [4:0] : s[4:0];
  assign \$8  = rtol_swizzle - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:87" *) cnt_ring_combined;
  assign \$9  = \$8 [5:0] + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:88" *) 5'h1a;
  assign swizz_minus_cnt_ring = \$8 [5] ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:90" *) \$9 [4:0] : \$8 [4:0];
  assign \$10  = load_start | (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:122" *) load_ring;
  assign left_out = \$10  ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:122" *) right_in : swizz_minus_cnt_ring;
  assign \s$18  = left_in + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:72" *) cnt_ring_combined;
  assign \$12  = \s$18 [4:0] >= (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:73" *) 5'h1a;
  assign \s_ge_26$20  = \$11  | (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:73" *) \$12 ;
  assign \$13  = \s$18  - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:74" *) 5'h1a;
  assign left_ptr = \s_ge_26$20  ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:75" *) \$13 [4:0] : \s$18 [4:0];
  assign \$15  = \$14  - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:87" *) cnt_ring_combined;
  assign \$16  = \$15 [5:0] + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:88" *) 5'h1a;
  assign swizz_l_minus_cnt_ring = \$15 [5] ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:90" *) \$16 [4:0] : \$15 [4:0];
  assign \$17  = cnt == (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:45" *) 5'h19;
  assign \$18  = cnt + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:48" *) 1'h1;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:21" *)
  always @(posedge clk)
    cnt <= \$19 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:24" *)
  always @(posedge clk)
    ring_setting <= \$20 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$4 ) begin end
    rtol_swizzle = 5'h00;
    casez (right_ptr)
      5'h00:
          rtol_swizzle = 5'h04;
      5'h01:
          rtol_swizzle = 5'h0a;
      5'h02:
          rtol_swizzle = 5'h0c;
      5'h03:
          rtol_swizzle = 5'h05;
      5'h04:
          rtol_swizzle = 5'h0b;
      5'h05:
          rtol_swizzle = 5'h06;
      5'h06:
          rtol_swizzle = 5'h03;
      5'h07:
          rtol_swizzle = 5'h10;
      5'h08:
          rtol_swizzle = 5'h15;
      5'h09:
          rtol_swizzle = 5'h19;
      5'h0a:
          rtol_swizzle = 5'h0d;
      5'h0b:
          rtol_swizzle = 5'h13;
      5'h0c:
          rtol_swizzle = 5'h0e;
      5'h0d:
          rtol_swizzle = 5'h16;
      5'h0e:
          rtol_swizzle = 5'h18;
      5'h0f:
          rtol_swizzle = 5'h07;
      5'h10:
          rtol_swizzle = 5'h17;
      5'h11:
          rtol_swizzle = 5'h14;
      5'h12:
          rtol_swizzle = 5'h12;
      5'h13:
          rtol_swizzle = 5'h0f;
      5'h14:
          rtol_swizzle = 5'h00;
      5'h15:
          rtol_swizzle = 5'h08;
      5'h16:
          rtol_swizzle = 5'h01;
      5'h17:
          rtol_swizzle = 5'h11;
      5'h18:
          rtol_swizzle = 5'h02;
      5'h19:
          rtol_swizzle = 5'h09;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$4 ) begin end
    \$14  = 5'h00;
    casez (left_ptr)
      5'h00:
          \$14  = 5'h14;
      5'h01:
          \$14  = 5'h16;
      5'h02:
          \$14  = 5'h18;
      5'h03:
          \$14  = 5'h06;
      5'h04:
          \$14  = 5'h00;
      5'h05:
          \$14  = 5'h03;
      5'h06:
          \$14  = 5'h05;
      5'h07:
          \$14  = 5'h0f;
      5'h08:
          \$14  = 5'h15;
      5'h09:
          \$14  = 5'h19;
      5'h0a:
          \$14  = 5'h01;
      5'h0b:
          \$14  = 5'h04;
      5'h0c:
          \$14  = 5'h02;
      5'h0d:
          \$14  = 5'h0a;
      5'h0e:
          \$14  = 5'h0c;
      5'h0f:
          \$14  = 5'h13;
      5'h10:
          \$14  = 5'h07;
      5'h11:
          \$14  = 5'h17;
      5'h12:
          \$14  = 5'h12;
      5'h13:
          \$14  = 5'h0b;
      5'h14:
          \$14  = 5'h11;
      5'h15:
          \$14  = 5'h08;
      5'h16:
          \$14  = 5'h0d;
      5'h17:
          \$14  = 5'h10;
      5'h18:
          \$14  = 5'h0e;
      5'h19:
          \$14  = 5'h09;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$4 ) begin end
    (* full_case = 32'd1 *)
    if (\$1 ) begin
      cnt_ring_combined = \$3 [4:0];
    end else begin
      cnt_ring_combined = \$4 [4:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$4 ) begin end
    \$19  = cnt;
    if (en) begin
      if (load_start) begin
        \$19  = right_in;
      end else if (load_ring) begin
      end else if (inc) begin
        (* full_case = 32'd1 *)
        if (\$17 ) begin
          \$19  = 5'h00;
        end else begin
          \$19  = \$18 [4:0];
        end
      end
    end
    if (rst) begin
      \$19  = 5'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$4 ) begin end
    \$20  = ring_setting;
    if (en) begin
      if (load_start) begin
      end else if (load_ring) begin
        \$20  = right_in;
      end
    end
    if (rst) begin
      \$20  = 5'h00;
    end
  end
  assign s_m_26 = \$7 [5:0];
  assign a_ext = { 1'h0, rtol_swizzle };
  assign b_ext = { 1'h0, cnt_ring_combined };
  assign \s$12  = \$8 [5:0];
  assign diff_plus_26 = \$9 [5:0];
  assign \s_m_26$21  = \$13 [5:0];
  assign \a_ext$23  = { 1'h0, \$14  };
  assign \b_ext$24  = { 1'h0, cnt_ring_combined };
  assign \s$25  = \$15 [5:0];
  assign \diff_plus_26$26  = \$16 [5:0];
  assign right_out = swizz_l_minus_cnt_ring;
  assign \$5  = s[5];
  assign \$11  = \s$18 [5];
endmodule

(* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:31" *)
(* generator = "Amaranth" *)
module \top.r1 (rst, right_in, is_at_turnover, left_out, swizz_l_minus_cnt_ring, left_in, en, load_start, load_ring, inc, clk);
  reg \$auto$verilog_backend.cc:2352:dump_module$5  = 0;
  wire \$1 ;
  wire \$10 ;
  wire \$11 ;
  wire \$12 ;
  wire [6:0] \$13 ;
  reg [4:0] \$14 ;
  wire [6:0] \$15 ;
  wire [6:0] \$16 ;
  wire \$17 ;
  wire [5:0] \$18 ;
  reg [4:0] \$19 ;
  wire [5:0] \$2 ;
  reg [4:0] \$20 ;
  wire [6:0] \$3 ;
  wire [5:0] \$4 ;
  wire \$5 ;
  wire \$6 ;
  wire [6:0] \$7 ;
  wire [6:0] \$8 ;
  wire [6:0] \$9 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:80" *)
  wire [5:0] a_ext;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:80" *)
  wire [5:0] \a_ext$23 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:81" *)
  wire [5:0] b_ext;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:81" *)
  wire [5:0] \b_ext$24 ;
  (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_ir.py:215" *)
  input clk;
  wire clk;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:21" *)
  reg [4:0] cnt = 5'h00;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:33" *)
  reg [4:0] cnt_ring_combined;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:82" *)
  wire [5:0] diff_plus_26;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:82" *)
  wire [5:0] \diff_plus_26$26 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:14" *)
  input en;
  wire en;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:17" *)
  input inc;
  wire inc;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:13" *)
  output is_at_turnover;
  wire is_at_turnover;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:10" *)
  input [4:0] left_in;
  wire [4:0] left_in;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:8" *)
  output [4:0] left_out;
  wire [4:0] left_out;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:27" *)
  wire [4:0] left_ptr;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:16" *)
  input load_ring;
  wire load_ring;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:15" *)
  input load_start;
  wire load_start;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:7" *)
  input [4:0] right_in;
  wire [4:0] right_in;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:11" *)
  wire [4:0] right_out;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:22" *)
  wire [4:0] right_ptr;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:24" *)
  reg [4:0] ring_setting = 5'h00;
  (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_ir.py:215" *)
  input rst;
  wire rst;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:23" *)
  reg [4:0] rtol_swizzle;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:68" *)
  wire [5:0] s;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:79" *)
  wire [5:0] \s$12 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:68" *)
  wire [5:0] \s$18 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:79" *)
  wire [5:0] \s$25 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:70" *)
  wire s_ge_26;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:70" *)
  wire \s_ge_26$20 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:69" *)
  wire [5:0] s_m_26;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:69" *)
  wire [5:0] \s_m_26$21 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:11" *)
  output [4:0] swizz_l_minus_cnt_ring;
  wire [4:0] swizz_l_minus_cnt_ring;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:119" *)
  wire [4:0] swizz_minus_cnt_ring;
  assign \$1  = ring_setting > (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:34" *) cnt;
  assign \$2  = ring_setting - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:35" *) cnt;
  assign \$3  = $signed(6'h1a) - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:35" *) $signed(\$2 );
  assign \$4  = cnt - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:37" *) ring_setting;
  assign is_at_turnover = cnt == (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:61" *) 3'h4;
  assign s = right_in + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:72" *) cnt_ring_combined;
  assign \$6  = s[4:0] >= (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:73" *) 5'h1a;
  assign s_ge_26 = \$5  | (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:73" *) \$6 ;
  assign \$7  = s - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:74" *) 5'h1a;
  assign right_ptr = s_ge_26 ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:75" *) \$7 [4:0] : s[4:0];
  assign \$8  = rtol_swizzle - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:87" *) cnt_ring_combined;
  assign \$9  = \$8 [5:0] + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:88" *) 5'h1a;
  assign swizz_minus_cnt_ring = \$8 [5] ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:90" *) \$9 [4:0] : \$8 [4:0];
  assign \$10  = load_start | (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:122" *) load_ring;
  assign left_out = \$10  ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:122" *) right_in : swizz_minus_cnt_ring;
  assign \s$18  = left_in + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:72" *) cnt_ring_combined;
  assign \$12  = \s$18 [4:0] >= (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:73" *) 5'h1a;
  assign \s_ge_26$20  = \$11  | (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:73" *) \$12 ;
  assign \$13  = \s$18  - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:74" *) 5'h1a;
  assign left_ptr = \s_ge_26$20  ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:75" *) \$13 [4:0] : \s$18 [4:0];
  assign \$15  = \$14  - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:87" *) cnt_ring_combined;
  assign \$16  = \$15 [5:0] + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:88" *) 5'h1a;
  assign swizz_l_minus_cnt_ring = \$15 [5] ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:90" *) \$16 [4:0] : \$15 [4:0];
  assign \$17  = cnt == (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:45" *) 5'h19;
  assign \$18  = cnt + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:48" *) 1'h1;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:21" *)
  always @(posedge clk)
    cnt <= \$19 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:24" *)
  always @(posedge clk)
    ring_setting <= \$20 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$5 ) begin end
    rtol_swizzle = 5'h00;
    casez (right_ptr)
      5'h00:
          rtol_swizzle = 5'h00;
      5'h01:
          rtol_swizzle = 5'h09;
      5'h02:
          rtol_swizzle = 5'h03;
      5'h03:
          rtol_swizzle = 5'h0a;
      5'h04:
          rtol_swizzle = 5'h12;
      5'h05:
          rtol_swizzle = 5'h08;
      5'h06:
          rtol_swizzle = 5'h11;
      5'h07:
          rtol_swizzle = 5'h14;
      5'h08:
          rtol_swizzle = 5'h17;
      5'h09:
          rtol_swizzle = 5'h01;
      5'h0a:
          rtol_swizzle = 5'h0b;
      5'h0b:
          rtol_swizzle = 5'h07;
      5'h0c:
          rtol_swizzle = 5'h16;
      5'h0d:
          rtol_swizzle = 5'h13;
      5'h0e:
          rtol_swizzle = 5'h0c;
      5'h0f:
          rtol_swizzle = 5'h02;
      5'h10:
          rtol_swizzle = 5'h10;
      5'h11:
          rtol_swizzle = 5'h06;
      5'h12:
          rtol_swizzle = 5'h19;
      5'h13:
          rtol_swizzle = 5'h0d;
      5'h14:
          rtol_swizzle = 5'h0f;
      5'h15:
          rtol_swizzle = 5'h18;
      5'h16:
          rtol_swizzle = 5'h05;
      5'h17:
          rtol_swizzle = 5'h15;
      5'h18:
          rtol_swizzle = 5'h0e;
      5'h19:
          rtol_swizzle = 5'h04;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$5 ) begin end
    \$14  = 5'h00;
    casez (left_ptr)
      5'h00:
          \$14  = 5'h00;
      5'h01:
          \$14  = 5'h09;
      5'h02:
          \$14  = 5'h0f;
      5'h03:
          \$14  = 5'h02;
      5'h04:
          \$14  = 5'h19;
      5'h05:
          \$14  = 5'h16;
      5'h06:
          \$14  = 5'h11;
      5'h07:
          \$14  = 5'h0b;
      5'h08:
          \$14  = 5'h05;
      5'h09:
          \$14  = 5'h01;
      5'h0a:
          \$14  = 5'h03;
      5'h0b:
          \$14  = 5'h0a;
      5'h0c:
          \$14  = 5'h0e;
      5'h0d:
          \$14  = 5'h13;
      5'h0e:
          \$14  = 5'h18;
      5'h0f:
          \$14  = 5'h14;
      5'h10:
          \$14  = 5'h10;
      5'h11:
          \$14  = 5'h06;
      5'h12:
          \$14  = 5'h04;
      5'h13:
          \$14  = 5'h0d;
      5'h14:
          \$14  = 5'h07;
      5'h15:
          \$14  = 5'h17;
      5'h16:
          \$14  = 5'h0c;
      5'h17:
          \$14  = 5'h08;
      5'h18:
          \$14  = 5'h15;
      5'h19:
          \$14  = 5'h12;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$5 ) begin end
    (* full_case = 32'd1 *)
    if (\$1 ) begin
      cnt_ring_combined = \$3 [4:0];
    end else begin
      cnt_ring_combined = \$4 [4:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$5 ) begin end
    \$19  = cnt;
    if (en) begin
      if (load_start) begin
        \$19  = right_in;
      end else if (load_ring) begin
      end else if (inc) begin
        (* full_case = 32'd1 *)
        if (\$17 ) begin
          \$19  = 5'h00;
        end else begin
          \$19  = \$18 [4:0];
        end
      end
    end
    if (rst) begin
      \$19  = 5'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$5 ) begin end
    \$20  = ring_setting;
    if (en) begin
      if (load_start) begin
      end else if (load_ring) begin
        \$20  = right_in;
      end
    end
    if (rst) begin
      \$20  = 5'h00;
    end
  end
  assign s_m_26 = \$7 [5:0];
  assign a_ext = { 1'h0, rtol_swizzle };
  assign b_ext = { 1'h0, cnt_ring_combined };
  assign \s$12  = \$8 [5:0];
  assign diff_plus_26 = \$9 [5:0];
  assign \s_m_26$21  = \$13 [5:0];
  assign \a_ext$23  = { 1'h0, \$14  };
  assign \b_ext$24  = { 1'h0, cnt_ring_combined };
  assign \s$25  = \$15 [5:0];
  assign \diff_plus_26$26  = \$16 [5:0];
  assign right_out = swizz_l_minus_cnt_ring;
  assign \$5  = s[5];
  assign \$11  = \s$18 [5];
endmodule

(* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:31" *)
(* generator = "Amaranth" *)
module \top.r2 (rst, right_in, is_at_turnover, left_out, swizz_l_minus_cnt_ring, left_in, en, load_start, load_ring, inc, clk);
  reg \$auto$verilog_backend.cc:2352:dump_module$6  = 0;
  wire \$1 ;
  wire \$10 ;
  wire \$11 ;
  wire \$12 ;
  wire [6:0] \$13 ;
  reg [4:0] \$14 ;
  wire [6:0] \$15 ;
  wire [6:0] \$16 ;
  wire \$17 ;
  wire [5:0] \$18 ;
  reg [4:0] \$19 ;
  wire [5:0] \$2 ;
  reg [4:0] \$20 ;
  wire [6:0] \$3 ;
  wire [5:0] \$4 ;
  wire \$5 ;
  wire \$6 ;
  wire [6:0] \$7 ;
  wire [6:0] \$8 ;
  wire [6:0] \$9 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:80" *)
  wire [5:0] a_ext;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:80" *)
  wire [5:0] \a_ext$23 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:81" *)
  wire [5:0] b_ext;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:81" *)
  wire [5:0] \b_ext$24 ;
  (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_ir.py:215" *)
  input clk;
  wire clk;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:21" *)
  reg [4:0] cnt = 5'h00;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:33" *)
  reg [4:0] cnt_ring_combined;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:82" *)
  wire [5:0] diff_plus_26;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:82" *)
  wire [5:0] \diff_plus_26$26 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:14" *)
  input en;
  wire en;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:17" *)
  input inc;
  wire inc;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:13" *)
  output is_at_turnover;
  wire is_at_turnover;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:10" *)
  input [4:0] left_in;
  wire [4:0] left_in;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:8" *)
  output [4:0] left_out;
  wire [4:0] left_out;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:27" *)
  wire [4:0] left_ptr;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:16" *)
  input load_ring;
  wire load_ring;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:15" *)
  input load_start;
  wire load_start;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:7" *)
  input [4:0] right_in;
  wire [4:0] right_in;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:11" *)
  wire [4:0] right_out;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:22" *)
  wire [4:0] right_ptr;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:24" *)
  reg [4:0] ring_setting = 5'h00;
  (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_ir.py:215" *)
  input rst;
  wire rst;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:23" *)
  reg [4:0] rtol_swizzle;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:68" *)
  wire [5:0] s;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:79" *)
  wire [5:0] \s$12 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:68" *)
  wire [5:0] \s$18 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:79" *)
  wire [5:0] \s$25 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:70" *)
  wire s_ge_26;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:70" *)
  wire \s_ge_26$20 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:69" *)
  wire [5:0] s_m_26;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:69" *)
  wire [5:0] \s_m_26$21 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:11" *)
  output [4:0] swizz_l_minus_cnt_ring;
  wire [4:0] swizz_l_minus_cnt_ring;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:119" *)
  wire [4:0] swizz_minus_cnt_ring;
  assign \$1  = ring_setting > (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:34" *) cnt;
  assign \$2  = ring_setting - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:35" *) cnt;
  assign \$3  = $signed(6'h1a) - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:35" *) $signed(\$2 );
  assign \$4  = cnt - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:37" *) ring_setting;
  assign is_at_turnover = cnt == (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:61" *) 5'h15;
  assign s = right_in + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:72" *) cnt_ring_combined;
  assign \$6  = s[4:0] >= (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:73" *) 5'h1a;
  assign s_ge_26 = \$5  | (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:73" *) \$6 ;
  assign \$7  = s - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:74" *) 5'h1a;
  assign right_ptr = s_ge_26 ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:75" *) \$7 [4:0] : s[4:0];
  assign \$8  = rtol_swizzle - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:87" *) cnt_ring_combined;
  assign \$9  = \$8 [5:0] + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:88" *) 5'h1a;
  assign swizz_minus_cnt_ring = \$8 [5] ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:90" *) \$9 [4:0] : \$8 [4:0];
  assign \$10  = load_start | (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:122" *) load_ring;
  assign left_out = \$10  ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:122" *) right_in : swizz_minus_cnt_ring;
  assign \s$18  = left_in + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:72" *) cnt_ring_combined;
  assign \$12  = \s$18 [4:0] >= (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:73" *) 5'h1a;
  assign \s_ge_26$20  = \$11  | (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:73" *) \$12 ;
  assign \$13  = \s$18  - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:74" *) 5'h1a;
  assign left_ptr = \s_ge_26$20  ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:75" *) \$13 [4:0] : \s$18 [4:0];
  assign \$15  = \$14  - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:87" *) cnt_ring_combined;
  assign \$16  = \$15 [5:0] + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:88" *) 5'h1a;
  assign swizz_l_minus_cnt_ring = \$15 [5] ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:90" *) \$16 [4:0] : \$15 [4:0];
  assign \$17  = cnt == (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:45" *) 5'h19;
  assign \$18  = cnt + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:48" *) 1'h1;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:21" *)
  always @(posedge clk)
    cnt <= \$19 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:24" *)
  always @(posedge clk)
    ring_setting <= \$20 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$6 ) begin end
    rtol_swizzle = 5'h00;
    casez (right_ptr)
      5'h00:
          rtol_swizzle = 5'h01;
      5'h01:
          rtol_swizzle = 5'h03;
      5'h02:
          rtol_swizzle = 5'h05;
      5'h03:
          rtol_swizzle = 5'h07;
      5'h04:
          rtol_swizzle = 5'h09;
      5'h05:
          rtol_swizzle = 5'h0b;
      5'h06:
          rtol_swizzle = 5'h02;
      5'h07:
          rtol_swizzle = 5'h0f;
      5'h08:
          rtol_swizzle = 5'h11;
      5'h09:
          rtol_swizzle = 5'h13;
      5'h0a:
          rtol_swizzle = 5'h17;
      5'h0b:
          rtol_swizzle = 5'h15;
      5'h0c:
          rtol_swizzle = 5'h19;
      5'h0d:
          rtol_swizzle = 5'h0d;
      5'h0e:
          rtol_swizzle = 5'h18;
      5'h0f:
          rtol_swizzle = 5'h04;
      5'h10:
          rtol_swizzle = 5'h08;
      5'h11:
          rtol_swizzle = 5'h16;
      5'h12:
          rtol_swizzle = 5'h06;
      5'h13:
          rtol_swizzle = 5'h00;
      5'h14:
          rtol_swizzle = 5'h0a;
      5'h15:
          rtol_swizzle = 5'h0c;
      5'h16:
          rtol_swizzle = 5'h14;
      5'h17:
          rtol_swizzle = 5'h12;
      5'h18:
          rtol_swizzle = 5'h10;
      5'h19:
          rtol_swizzle = 5'h0e;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$6 ) begin end
    \$14  = 5'h00;
    casez (left_ptr)
      5'h00:
          \$14  = 5'h13;
      5'h01:
          \$14  = 5'h00;
      5'h02:
          \$14  = 5'h06;
      5'h03:
          \$14  = 5'h01;
      5'h04:
          \$14  = 5'h0f;
      5'h05:
          \$14  = 5'h02;
      5'h06:
          \$14  = 5'h12;
      5'h07:
          \$14  = 5'h03;
      5'h08:
          \$14  = 5'h10;
      5'h09:
          \$14  = 5'h04;
      5'h0a:
          \$14  = 5'h14;
      5'h0b:
          \$14  = 5'h05;
      5'h0c:
          \$14  = 5'h15;
      5'h0d:
          \$14  = 5'h0d;
      5'h0e:
          \$14  = 5'h19;
      5'h0f:
          \$14  = 5'h07;
      5'h10:
          \$14  = 5'h18;
      5'h11:
          \$14  = 5'h08;
      5'h12:
          \$14  = 5'h17;
      5'h13:
          \$14  = 5'h09;
      5'h14:
          \$14  = 5'h16;
      5'h15:
          \$14  = 5'h0b;
      5'h16:
          \$14  = 5'h11;
      5'h17:
          \$14  = 5'h0a;
      5'h18:
          \$14  = 5'h0e;
      5'h19:
          \$14  = 5'h0c;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$6 ) begin end
    (* full_case = 32'd1 *)
    if (\$1 ) begin
      cnt_ring_combined = \$3 [4:0];
    end else begin
      cnt_ring_combined = \$4 [4:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$6 ) begin end
    \$19  = cnt;
    if (en) begin
      if (load_start) begin
        \$19  = right_in;
      end else if (load_ring) begin
      end else if (inc) begin
        (* full_case = 32'd1 *)
        if (\$17 ) begin
          \$19  = 5'h00;
        end else begin
          \$19  = \$18 [4:0];
        end
      end
    end
    if (rst) begin
      \$19  = 5'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$6 ) begin end
    \$20  = ring_setting;
    if (en) begin
      if (load_start) begin
      end else if (load_ring) begin
        \$20  = right_in;
      end
    end
    if (rst) begin
      \$20  = 5'h00;
    end
  end
  assign s_m_26 = \$7 [5:0];
  assign a_ext = { 1'h0, rtol_swizzle };
  assign b_ext = { 1'h0, cnt_ring_combined };
  assign \s$12  = \$8 [5:0];
  assign diff_plus_26 = \$9 [5:0];
  assign \s_m_26$21  = \$13 [5:0];
  assign \a_ext$23  = { 1'h0, \$14  };
  assign \b_ext$24  = { 1'h0, cnt_ring_combined };
  assign \s$25  = \$15 [5:0];
  assign \diff_plus_26$26  = \$16 [5:0];
  assign right_out = swizz_l_minus_cnt_ring;
  assign \$5  = s[5];
  assign \$11  = \s$18 [5];
endmodule

(* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:163" *)
(* generator = "Amaranth" *)
module \top.ref (left_out, right_ptr);
  reg \$auto$verilog_backend.cc:2352:dump_module$7  = 0;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:21" *)
  wire [4:0] cnt;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:13" *)
  wire is_at_turnover;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:8" *)
  output [4:0] left_out;
  reg [4:0] left_out;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:27" *)
  wire [4:0] left_ptr;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:7" *)
  wire [4:0] right_in;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:11" *)
  wire [4:0] right_out;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:7" *)
  input [4:0] right_ptr;
  wire [4:0] right_ptr;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:23" *)
  wire [4:0] rtol_swizzle;
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$7 ) begin end
    left_out = 5'h00;
    casez (right_ptr)
      5'h00:
          left_out = 5'h18;
      5'h01:
          left_out = 5'h11;
      5'h02:
          left_out = 5'h14;
      5'h03:
          left_out = 5'h07;
      5'h04:
          left_out = 5'h10;
      5'h05:
          left_out = 5'h12;
      5'h06:
          left_out = 5'h0b;
      5'h07:
          left_out = 5'h03;
      5'h08:
          left_out = 5'h0f;
      5'h09:
          left_out = 5'h17;
      5'h0a:
          left_out = 5'h0d;
      5'h0b:
          left_out = 5'h06;
      5'h0c:
          left_out = 5'h0e;
      5'h0d:
          left_out = 5'h0a;
      5'h0e:
          left_out = 5'h0c;
      5'h0f:
          left_out = 5'h08;
      5'h10:
          left_out = 5'h04;
      5'h11:
          left_out = 5'h01;
      5'h12:
          left_out = 5'h05;
      5'h13:
          left_out = 5'h19;
      5'h14:
          left_out = 5'h02;
      5'h15:
          left_out = 5'h16;
      5'h16:
          left_out = 5'h15;
      5'h17:
          left_out = 5'h09;
      5'h18:
          left_out = 5'h00;
      5'h19:
          left_out = 5'h13;
    endcase
  end
  assign right_in = right_ptr;
  assign right_out = 5'h00;
  assign is_at_turnover = 1'h0;
  assign rtol_swizzle = 5'h00;
  assign cnt = 5'h00;
  assign left_ptr = 5'h00;
endmodule
