/* Generated by Amaranth Yosys 0.40 (PyPI ver 0.40.0.0.post100, git sha1 a1bb0255d) */

(* top =  1  *)
(* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/top.py:33" *)
(* generator = "Amaranth" *)
module top(clk, rst, uo_out, ui_in);
  reg \$auto$verilog_backend.cc:2352:dump_module$1  = 0;
  wire \$1 ;
  wire \$2 ;
  reg [4:0] \$3 ;
  reg [4:0] \$4  = 5'h00;
  (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_ir.py:215" *)
  input clk;
  wire clk;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:17" *)
  wire [2:0] cmd;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:14" *)
  wire en;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:21" *)
  wire [2:0] \en$24 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:14" *)
  wire \en$25 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:14" *)
  wire \en$26 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:14" *)
  wire \en$27 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:17" *)
  wire inc;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:24" *)
  wire [2:0] \inc$39 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:17" *)
  wire \inc$40 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:17" *)
  wire \inc$41 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:17" *)
  wire \inc$42 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:18" *)
  wire [2:0] is_at_turnover;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:13" *)
  wire \is_at_turnover$44 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:13" *)
  wire \is_at_turnover$45 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:13" *)
  wire \is_at_turnover$46 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:10" *)
  wire [4:0] left_in;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:10" *)
  wire [4:0] \left_in$16 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:10" *)
  wire [4:0] \left_in$18 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:10" *)
  wire [4:0] \left_in$20 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:8" *)
  wire [4:0] left_out;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:8" *)
  wire [4:0] \left_out$12 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:8" *)
  wire [4:0] \left_out$14 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:8" *)
  wire [4:0] \left_out$17 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:16" *)
  wire load_ring;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:23" *)
  wire \load_ring$34 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:16" *)
  wire \load_ring$35 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:16" *)
  wire \load_ring$36 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:16" *)
  wire \load_ring$37 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:15" *)
  wire load_start;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:22" *)
  wire \load_start$29 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:15" *)
  wire \load_start$30 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:15" *)
  wire \load_start$31 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:15" *)
  wire \load_start$32 ;
  (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/lib/memory.py:240" *)
  wire [4:0] rd_port_ltor__addr;
  (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/lib/memory.py:241" *)
  wire [4:0] rd_port_ltor__data;
  (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/lib/memory.py:240" *)
  wire [4:0] rd_port_rtol__addr;
  (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/lib/memory.py:241" *)
  wire [4:0] rd_port_rtol__data;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:20" *)
  wire ready;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:7" *)
  wire [4:0] right_in;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:7" *)
  wire [4:0] \right_in$11 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:7" *)
  wire [4:0] \right_in$13 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:7" *)
  wire [4:0] \right_in$9 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/top.py:55" *)
  wire [4:0] right_out;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:11" *)
  wire [4:0] \right_out$19 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:11" *)
  wire [4:0] \right_out$21 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:11" *)
  wire [4:0] \right_out$22 ;
  (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_ir.py:215" *)
  input rst;
  wire rst;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/top.py:10" *)
  input [7:0] ui_in;
  wire [7:0] ui_in;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/top.py:11" *)
  output [5:0] uo_out;
  wire [5:0] uo_out;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/top.py:42" *)
  reg [4:0] memory [25:0];
  initial begin
    memory[0] = 5'h0d;
    memory[1] = 5'h01;
    memory[2] = 5'h02;
    memory[3] = 5'h03;
    memory[4] = 5'h04;
    memory[5] = 5'h05;
    memory[6] = 5'h06;
    memory[7] = 5'h07;
    memory[8] = 5'h08;
    memory[9] = 5'h09;
    memory[10] = 5'h0a;
    memory[11] = 5'h0b;
    memory[12] = 5'h0c;
    memory[13] = 5'h00;
    memory[14] = 5'h0e;
    memory[15] = 5'h0f;
    memory[16] = 5'h10;
    memory[17] = 5'h11;
    memory[18] = 5'h12;
    memory[19] = 5'h13;
    memory[20] = 5'h14;
    memory[21] = 5'h15;
    memory[22] = 5'h16;
    memory[23] = 5'h17;
    memory[24] = 5'h18;
    memory[25] = 5'h19;
  end
  assign rd_port_ltor__data = memory[rd_port_ltor__addr];
  assign right_in = memory[ui_in[4:0]];
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/top.py:11" *)
  always @(posedge clk)
    \$4  <= \$3 ;
  assign \$1  = ui_in[7:5] == (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/top.py:68" *) 3'h4;
  assign \$2  = ready & (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/top.py:68" *) \$1 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/top.py:38" *)
  \top.fsm  fsm (
    .clk(clk),
    .cmd(ui_in[7:5]),
    .en(\en$24 ),
    .inc(\inc$39 ),
    .is_at_turnover(is_at_turnover),
    .load_ring(load_ring),
    .load_start(load_start),
    .ready(ready),
    .rst(rst)
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/top.py:34" *)
  \top.r0  r0 (
    .clk(clk),
    .en(\en$24 [0]),
    .inc(\inc$39 [0]),
    .is_at_turnover(\is_at_turnover$44 ),
    .left_in(\left_in$20 ),
    .left_out(\right_in$9 ),
    .load_ring(load_ring),
    .load_start(load_start),
    .right_in(right_in),
    .rst(rst),
    .swizz_l_minus_cnt_ring(rd_port_ltor__addr)
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/top.py:35" *)
  \top.r1  r1 (
    .clk(clk),
    .en(\en$24 [1]),
    .inc(\inc$39 [1]),
    .is_at_turnover(\is_at_turnover$45 ),
    .left_in(\left_in$18 ),
    .left_out(\right_in$11 ),
    .load_ring(load_ring),
    .load_start(load_start),
    .right_in(\right_in$9 ),
    .rst(rst),
    .swizz_l_minus_cnt_ring(\left_in$20 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/top.py:36" *)
  \top.r2  r2 (
    .clk(clk),
    .en(\en$24 [2]),
    .inc(\inc$39 [2]),
    .is_at_turnover(\is_at_turnover$46 ),
    .left_in(\left_in$16 ),
    .left_out(\right_in$13 ),
    .load_ring(load_ring),
    .load_start(load_start),
    .right_in(\right_in$11 ),
    .rst(rst),
    .swizz_l_minus_cnt_ring(\left_in$18 )
  );
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/top.py:37" *)
  \top.ref  \ref  (
    .left_out(\left_in$16 ),
    .right_ptr(\right_in$13 )
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$3  = \$4 ;
    if (\$2 ) begin
      \$3  = rd_port_ltor__data;
    end
    if (rst) begin
      \$3  = 5'h00;
    end
  end
  assign rd_port_rtol__addr = ui_in[4:0];
  assign right_out = rd_port_ltor__addr;
  assign rd_port_rtol__data = right_in;
  assign left_out = \right_in$9 ;
  assign \left_out$12  = \right_in$11 ;
  assign \left_out$14  = \right_in$13 ;
  assign left_in = 5'h00;
  assign \left_out$17  = \left_in$16 ;
  assign \right_out$19  = \left_in$18 ;
  assign \right_out$21  = \left_in$20 ;
  assign \right_out$22  = rd_port_ltor__addr;
  assign en = \en$24 [0];
  assign \en$25  = \en$24 [1];
  assign \en$26  = \en$24 [2];
  assign \en$27  = 1'h0;
  assign \load_start$29  = load_start;
  assign \load_start$30  = load_start;
  assign \load_start$31  = load_start;
  assign \load_start$32  = 1'h0;
  assign \load_ring$34  = load_ring;
  assign \load_ring$35  = load_ring;
  assign \load_ring$36  = load_ring;
  assign \load_ring$37  = 1'h0;
  assign inc = \inc$39 [0];
  assign \inc$40  = \inc$39 [1];
  assign \inc$41  = \inc$39 [2];
  assign \inc$42  = 1'h0;
  assign cmd = ui_in[7:5];
  assign uo_out = { ready, \$4  };
  assign is_at_turnover[2] = \is_at_turnover$46 ;
  assign is_at_turnover[1] = \is_at_turnover$45 ;
  assign is_at_turnover[0] = \is_at_turnover$44 ;
endmodule

(* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:31" *)
(* generator = "Amaranth" *)
module \top.fsm (clk, rst, is_at_turnover, en, ready, load_start, load_ring, inc, cmd);
  reg \$auto$verilog_backend.cc:2352:dump_module$2  = 0;
  wire \$1 ;
  wire [2:0] \$10 ;
  wire \$11 ;
  wire \$12 ;
  wire \$13 ;
  reg [1:0] \$14 ;
  reg [2:0] \$15 ;
  reg [2:0] \$16 ;
  reg \$17 ;
  wire \$2 ;
  wire \$3 ;
  wire \$4 ;
  wire \$5 ;
  wire \$6 ;
  wire \$7 ;
  wire \$8 ;
  wire [2:0] \$9 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:33" *)
  reg [1:0] active;
  (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_ir.py:215" *)
  input clk;
  wire clk;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:17" *)
  input [2:0] cmd;
  wire [2:0] cmd;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:32" *)
  reg [1:0] cnt = 2'h0;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:35" *)
  reg double_step = 1'h0;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:21" *)
  output [2:0] en;
  reg [2:0] en;
  (* enum_base_type = "fsmState" *)
  (* enum_value_000 = "Initial/0" *)
  (* enum_value_001 = "Get command/1" *)
  (* enum_value_010 = "Load start/2" *)
  (* enum_value_011 = "Load ring/3" *)
  (* enum_value_100 = "Inc Rotor 0/4" *)
  (* enum_value_101 = "Inc Rotor 1/5" *)
  (* enum_value_110 = "Check Rotor 1 Turnover/6" *)
  (* enum_value_111 = "Inc Rotor 2/7" *)
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:60" *)
  reg [2:0] fsm_state = 3'h0;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:34" *)
  output [2:0] inc;
  reg [2:0] inc = 3'h0;
  (* init = 3'h0 *)
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:34" *)
  wire [2:0] \inc$1 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:18" *)
  input [2:0] is_at_turnover;
  wire [2:0] is_at_turnover;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:23" *)
  output load_ring;
  reg load_ring;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:22" *)
  output load_start;
  reg load_start;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:20" *)
  output ready;
  reg ready;
  (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_ir.py:215" *)
  input rst;
  wire rst;
  assign \$1  = ! (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) fsm_state;
  assign \$2  = fsm_state == (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) 1'h1;
  assign \$3  = fsm_state == (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) 2'h2;
  assign \$4  = fsm_state == (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) 2'h3;
  assign \$5  = fsm_state == (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) 3'h4;
  assign \$6  = fsm_state == (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) 3'h5;
  assign \$7  = fsm_state == (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) 3'h6;
  assign \$8  = fsm_state == (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_dsl.py:486" *) 3'h7;
  assign \$9  = cnt + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:81" *) 1'h1;
  assign \$10  = cnt + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:84" *) 1'h1;
  assign \$11  = cnt == (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:98" *) 2'h3;
  assign \$12  = cnt == (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:109" *) 2'h3;
  assign \$13  = is_at_turnover[0] | (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:120" *) double_step;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:32" *)
  always @(posedge clk)
    cnt <= \$14 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:60" *)
  always @(posedge clk)
    fsm_state <= \$15 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:34" *)
  always @(posedge clk)
    inc <= \$16 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/fsm.py:35" *)
  always @(posedge clk)
    double_step <= \$17 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    (* full_case = 32'd1 *)
    casez (active)
      2'h1:
          en = 3'h1;
      2'h2:
          en = 3'h2;
      2'h3:
          en = 3'h4;
      default:
          en = 3'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    ready = 1'h0;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          ready = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    load_start = 1'h0;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          load_start = 1'h0;
      3'h2:
          load_start = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    load_ring = 1'h0;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          load_ring = 1'h0;
      3'h2:
          /* empty */;
      3'h3:
          load_ring = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    active = 2'h0;
    (* full_case = 32'd1 *)
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          /* empty */;
      3'h2:
          active = cnt;
      3'h3:
          active = cnt;
      3'h4:
          active = cnt;
      3'h5:
          active = cnt;
      3'h6:
          /* empty */;
      3'h7:
          active = cnt;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    \$14  = cnt;
    (* full_case = 32'd1 *)
    casez (fsm_state)
      3'h0:
          \$14  = 2'h0;
      3'h1:
        begin
          \$14  = 2'h0;
          casez (cmd)
            3'h3:
                /* empty */;
            3'h1:
                \$14  = \$9 [1:0];
            3'h2:
                \$14  = \$10 [1:0];
            3'h4:
                \$14  = 2'h1;
          endcase
        end
      3'h2:
          if (\$11 ) begin
            \$14  = 2'h0;
          end
      3'h3:
          if (\$12 ) begin
            \$14  = 2'h0;
          end
      3'h4:
          if (\$13 ) begin
            \$14  = 2'h2;
          end
      3'h5:
          \$14  = 2'h2;
      3'h6:
          if (is_at_turnover[1]) begin
          end else if (double_step) begin
            \$14  = 2'h3;
          end
      3'h7:
          \$14  = 2'h0;
    endcase
    if (rst) begin
      \$14  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    (* full_case = 32'd1 *)
    casez (fsm_state)
      3'h0:
          \$15  = 3'h1;
      3'h1:
          (* full_case = 32'd1 *)
          casez (cmd)
            3'h3:
                \$15  = 3'h0;
            3'h1:
                \$15  = 3'h2;
            3'h2:
                \$15  = 3'h3;
            3'h4:
                \$15  = 3'h4;
            default:
                \$15  = 3'h1;
          endcase
      3'h2:
          (* full_case = 32'd1 *)
          if (\$11 ) begin
            \$15  = 3'h1;
          end else begin
            \$15  = 3'h1;
          end
      3'h3:
          (* full_case = 32'd1 *)
          if (\$12 ) begin
            \$15  = 3'h1;
          end else begin
            \$15  = 3'h1;
          end
      3'h4:
          (* full_case = 32'd1 *)
          if (\$13 ) begin
            \$15  = 3'h5;
          end else begin
            \$15  = 3'h1;
          end
      3'h5:
          \$15  = 3'h6;
      3'h6:
          (* full_case = 32'd1 *)
          if (is_at_turnover[1]) begin
            \$15  = 3'h1;
          end else if (double_step) begin
            \$15  = 3'h7;
          end else begin
            \$15  = 3'h1;
          end
      3'h7:
          \$15  = 3'h1;
    endcase
    if (rst) begin
      \$15  = 3'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    \$16  = inc;
    (* full_case = 32'd1 *)
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
        begin
          \$16  = 3'h0;
          casez (cmd)
            3'h3:
                /* empty */;
            3'h1:
                /* empty */;
            3'h2:
                /* empty */;
            3'h4:
                \$16 [0] = 1'h1;
          endcase
        end
      3'h2:
          /* empty */;
      3'h3:
          /* empty */;
      3'h4:
          if (\$13 ) begin
            \$16 [0] = 1'h0;
            \$16 [1] = 1'h1;
          end
      3'h5:
          \$16 [1] = 1'h0;
      3'h6:
        begin
          \$16 [0] = 1'h0;
          \$16 [1] = 1'h0;
          if (is_at_turnover[1]) begin
          end else if (double_step) begin
            \$16 [2] = 1'h1;
          end
        end
      3'h7:
        begin
          \$16 [0] = 1'h0;
          \$16 [1] = 1'h0;
          \$16 [2] = 1'h0;
        end
    endcase
    if (rst) begin
      \$16  = 3'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    \$17  = double_step;
    (* full_case = 32'd1 *)
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          /* empty */;
      3'h2:
          /* empty */;
      3'h3:
          /* empty */;
      3'h4:
          /* empty */;
      3'h5:
          /* empty */;
      3'h6:
          if (is_at_turnover[1]) begin
            \$17  = 1'h1;
          end
      3'h7:
          \$17  = 1'h0;
    endcase
    if (rst) begin
      \$17  = 1'h0;
    end
  end
  assign \inc$1  = inc;
endmodule

(* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:31" *)
(* generator = "Amaranth" *)
module \top.r0 (rst, is_at_turnover, left_out, swizz_l_minus_cnt_ring, left_in, right_in, en, load_start, load_ring, inc, clk);
  reg \$auto$verilog_backend.cc:2352:dump_module$3  = 0;
  wire \$1 ;
  wire \$10 ;
  wire \$11 ;
  wire \$12 ;
  wire [6:0] \$13 ;
  reg [4:0] \$14 ;
  wire [6:0] \$15 ;
  wire [6:0] \$16 ;
  wire \$17 ;
  wire [5:0] \$18 ;
  reg [4:0] \$19 ;
  wire [5:0] \$2 ;
  reg [4:0] \$20 ;
  wire [6:0] \$3 ;
  wire [5:0] \$4 ;
  wire \$5 ;
  wire \$6 ;
  wire [6:0] \$7 ;
  wire [6:0] \$8 ;
  wire [6:0] \$9 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:80" *)
  wire [5:0] a_ext;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:80" *)
  wire [5:0] \a_ext$23 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:81" *)
  wire [5:0] b_ext;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:81" *)
  wire [5:0] \b_ext$24 ;
  (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_ir.py:215" *)
  input clk;
  wire clk;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:21" *)
  reg [4:0] cnt = 5'h00;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:33" *)
  reg [4:0] cnt_ring_combined;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:82" *)
  wire [5:0] diff_plus_26;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:82" *)
  wire [5:0] \diff_plus_26$26 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:14" *)
  input en;
  wire en;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:17" *)
  input inc;
  wire inc;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:13" *)
  output is_at_turnover;
  wire is_at_turnover;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:10" *)
  input [4:0] left_in;
  wire [4:0] left_in;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:8" *)
  output [4:0] left_out;
  wire [4:0] left_out;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:27" *)
  wire [4:0] left_ptr;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:16" *)
  input load_ring;
  wire load_ring;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:15" *)
  input load_start;
  wire load_start;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:7" *)
  input [4:0] right_in;
  wire [4:0] right_in;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:11" *)
  wire [4:0] right_out;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:22" *)
  wire [4:0] right_ptr;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:24" *)
  reg [4:0] ring_setting = 5'h00;
  (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_ir.py:215" *)
  input rst;
  wire rst;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:23" *)
  reg [4:0] rtol_swizzle;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:68" *)
  wire [5:0] s;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:79" *)
  wire [5:0] \s$12 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:68" *)
  wire [5:0] \s$18 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:79" *)
  wire [5:0] \s$25 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:70" *)
  wire s_ge_26;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:70" *)
  wire \s_ge_26$20 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:69" *)
  wire [5:0] s_m_26;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:69" *)
  wire [5:0] \s_m_26$21 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:11" *)
  output [4:0] swizz_l_minus_cnt_ring;
  wire [4:0] swizz_l_minus_cnt_ring;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:119" *)
  wire [4:0] swizz_minus_cnt_ring;
  assign \$1  = ring_setting > (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:34" *) cnt;
  assign \$2  = ring_setting - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:35" *) cnt;
  assign \$3  = $signed(6'h1a) - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:35" *) $signed(\$2 );
  assign \$4  = cnt - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:37" *) ring_setting;
  assign is_at_turnover = cnt == (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:61" *) 5'h10;
  assign s = right_in + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:72" *) cnt_ring_combined;
  assign \$6  = s[4:0] >= (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:73" *) 5'h1a;
  assign s_ge_26 = \$5  | (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:73" *) \$6 ;
  assign \$7  = s - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:74" *) 5'h1a;
  assign right_ptr = s_ge_26 ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:75" *) \$7 [4:0] : s[4:0];
  assign \$8  = rtol_swizzle - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:87" *) cnt_ring_combined;
  assign \$9  = \$8 [5:0] + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:88" *) 5'h1a;
  assign swizz_minus_cnt_ring = \$8 [5] ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:90" *) \$9 [4:0] : \$8 [4:0];
  assign \$10  = load_start | (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:122" *) load_ring;
  assign left_out = \$10  ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:122" *) right_in : swizz_minus_cnt_ring;
  assign \s$18  = left_in + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:72" *) cnt_ring_combined;
  assign \$12  = \s$18 [4:0] >= (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:73" *) 5'h1a;
  assign \s_ge_26$20  = \$11  | (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:73" *) \$12 ;
  assign \$13  = \s$18  - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:74" *) 5'h1a;
  assign left_ptr = \s_ge_26$20  ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:75" *) \$13 [4:0] : \s$18 [4:0];
  assign \$15  = \$14  - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:87" *) cnt_ring_combined;
  assign \$16  = \$15 [5:0] + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:88" *) 5'h1a;
  assign swizz_l_minus_cnt_ring = \$15 [5] ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:90" *) \$16 [4:0] : \$15 [4:0];
  assign \$17  = cnt == (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:45" *) 5'h19;
  assign \$18  = cnt + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:48" *) 1'h1;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:21" *)
  always @(posedge clk)
    cnt <= \$19 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:24" *)
  always @(posedge clk)
    ring_setting <= \$20 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$3 ) begin end
    rtol_swizzle = 5'h00;
    casez (right_ptr)
      5'h00:
          rtol_swizzle = 5'h04;
      5'h01:
          rtol_swizzle = 5'h0a;
      5'h02:
          rtol_swizzle = 5'h0c;
      5'h03:
          rtol_swizzle = 5'h05;
      5'h04:
          rtol_swizzle = 5'h0b;
      5'h05:
          rtol_swizzle = 5'h06;
      5'h06:
          rtol_swizzle = 5'h03;
      5'h07:
          rtol_swizzle = 5'h10;
      5'h08:
          rtol_swizzle = 5'h15;
      5'h09:
          rtol_swizzle = 5'h19;
      5'h0a:
          rtol_swizzle = 5'h0d;
      5'h0b:
          rtol_swizzle = 5'h13;
      5'h0c:
          rtol_swizzle = 5'h0e;
      5'h0d:
          rtol_swizzle = 5'h16;
      5'h0e:
          rtol_swizzle = 5'h18;
      5'h0f:
          rtol_swizzle = 5'h07;
      5'h10:
          rtol_swizzle = 5'h17;
      5'h11:
          rtol_swizzle = 5'h14;
      5'h12:
          rtol_swizzle = 5'h12;
      5'h13:
          rtol_swizzle = 5'h0f;
      5'h14:
          rtol_swizzle = 5'h00;
      5'h15:
          rtol_swizzle = 5'h08;
      5'h16:
          rtol_swizzle = 5'h01;
      5'h17:
          rtol_swizzle = 5'h11;
      5'h18:
          rtol_swizzle = 5'h02;
      5'h19:
          rtol_swizzle = 5'h09;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$3 ) begin end
    \$14  = 5'h00;
    casez (left_ptr)
      5'h00:
          \$14  = 5'h14;
      5'h01:
          \$14  = 5'h16;
      5'h02:
          \$14  = 5'h18;
      5'h03:
          \$14  = 5'h06;
      5'h04:
          \$14  = 5'h00;
      5'h05:
          \$14  = 5'h03;
      5'h06:
          \$14  = 5'h05;
      5'h07:
          \$14  = 5'h0f;
      5'h08:
          \$14  = 5'h15;
      5'h09:
          \$14  = 5'h19;
      5'h0a:
          \$14  = 5'h01;
      5'h0b:
          \$14  = 5'h04;
      5'h0c:
          \$14  = 5'h02;
      5'h0d:
          \$14  = 5'h0a;
      5'h0e:
          \$14  = 5'h0c;
      5'h0f:
          \$14  = 5'h13;
      5'h10:
          \$14  = 5'h07;
      5'h11:
          \$14  = 5'h17;
      5'h12:
          \$14  = 5'h12;
      5'h13:
          \$14  = 5'h0b;
      5'h14:
          \$14  = 5'h11;
      5'h15:
          \$14  = 5'h08;
      5'h16:
          \$14  = 5'h0d;
      5'h17:
          \$14  = 5'h10;
      5'h18:
          \$14  = 5'h0e;
      5'h19:
          \$14  = 5'h09;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$3 ) begin end
    (* full_case = 32'd1 *)
    if (\$1 ) begin
      cnt_ring_combined = \$3 [4:0];
    end else begin
      cnt_ring_combined = \$4 [4:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$3 ) begin end
    \$19  = cnt;
    if (en) begin
      if (load_start) begin
        \$19  = right_in;
      end else if (load_ring) begin
      end else if (inc) begin
        (* full_case = 32'd1 *)
        if (\$17 ) begin
          \$19  = 5'h00;
        end else begin
          \$19  = \$18 [4:0];
        end
      end
    end
    if (rst) begin
      \$19  = 5'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$3 ) begin end
    \$20  = ring_setting;
    if (en) begin
      if (load_start) begin
      end else if (load_ring) begin
        \$20  = right_in;
      end
    end
    if (rst) begin
      \$20  = 5'h00;
    end
  end
  assign s_m_26 = \$7 [5:0];
  assign a_ext = { 1'h0, rtol_swizzle };
  assign b_ext = { 1'h0, cnt_ring_combined };
  assign \s$12  = \$8 [5:0];
  assign diff_plus_26 = \$9 [5:0];
  assign \s_m_26$21  = \$13 [5:0];
  assign \a_ext$23  = { 1'h0, \$14  };
  assign \b_ext$24  = { 1'h0, cnt_ring_combined };
  assign \s$25  = \$15 [5:0];
  assign \diff_plus_26$26  = \$16 [5:0];
  assign right_out = swizz_l_minus_cnt_ring;
  assign \$5  = s[5];
  assign \$11  = \s$18 [5];
endmodule

(* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:31" *)
(* generator = "Amaranth" *)
module \top.r1 (rst, right_in, is_at_turnover, left_out, swizz_l_minus_cnt_ring, left_in, en, load_start, load_ring, inc, clk);
  reg \$auto$verilog_backend.cc:2352:dump_module$4  = 0;
  wire \$1 ;
  wire \$10 ;
  wire \$11 ;
  wire \$12 ;
  wire [6:0] \$13 ;
  reg [4:0] \$14 ;
  wire [6:0] \$15 ;
  wire [6:0] \$16 ;
  wire \$17 ;
  wire [5:0] \$18 ;
  reg [4:0] \$19 ;
  wire [5:0] \$2 ;
  reg [4:0] \$20 ;
  wire [6:0] \$3 ;
  wire [5:0] \$4 ;
  wire \$5 ;
  wire \$6 ;
  wire [6:0] \$7 ;
  wire [6:0] \$8 ;
  wire [6:0] \$9 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:80" *)
  wire [5:0] a_ext;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:80" *)
  wire [5:0] \a_ext$23 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:81" *)
  wire [5:0] b_ext;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:81" *)
  wire [5:0] \b_ext$24 ;
  (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_ir.py:215" *)
  input clk;
  wire clk;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:21" *)
  reg [4:0] cnt = 5'h00;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:33" *)
  reg [4:0] cnt_ring_combined;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:82" *)
  wire [5:0] diff_plus_26;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:82" *)
  wire [5:0] \diff_plus_26$26 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:14" *)
  input en;
  wire en;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:17" *)
  input inc;
  wire inc;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:13" *)
  output is_at_turnover;
  wire is_at_turnover;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:10" *)
  input [4:0] left_in;
  wire [4:0] left_in;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:8" *)
  output [4:0] left_out;
  wire [4:0] left_out;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:27" *)
  wire [4:0] left_ptr;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:16" *)
  input load_ring;
  wire load_ring;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:15" *)
  input load_start;
  wire load_start;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:7" *)
  input [4:0] right_in;
  wire [4:0] right_in;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:11" *)
  wire [4:0] right_out;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:22" *)
  wire [4:0] right_ptr;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:24" *)
  reg [4:0] ring_setting = 5'h00;
  (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_ir.py:215" *)
  input rst;
  wire rst;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:23" *)
  reg [4:0] rtol_swizzle;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:68" *)
  wire [5:0] s;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:79" *)
  wire [5:0] \s$12 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:68" *)
  wire [5:0] \s$18 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:79" *)
  wire [5:0] \s$25 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:70" *)
  wire s_ge_26;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:70" *)
  wire \s_ge_26$20 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:69" *)
  wire [5:0] s_m_26;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:69" *)
  wire [5:0] \s_m_26$21 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:11" *)
  output [4:0] swizz_l_minus_cnt_ring;
  wire [4:0] swizz_l_minus_cnt_ring;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:119" *)
  wire [4:0] swizz_minus_cnt_ring;
  assign \$1  = ring_setting > (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:34" *) cnt;
  assign \$2  = ring_setting - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:35" *) cnt;
  assign \$3  = $signed(6'h1a) - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:35" *) $signed(\$2 );
  assign \$4  = cnt - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:37" *) ring_setting;
  assign is_at_turnover = cnt == (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:61" *) 3'h4;
  assign s = right_in + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:72" *) cnt_ring_combined;
  assign \$6  = s[4:0] >= (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:73" *) 5'h1a;
  assign s_ge_26 = \$5  | (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:73" *) \$6 ;
  assign \$7  = s - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:74" *) 5'h1a;
  assign right_ptr = s_ge_26 ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:75" *) \$7 [4:0] : s[4:0];
  assign \$8  = rtol_swizzle - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:87" *) cnt_ring_combined;
  assign \$9  = \$8 [5:0] + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:88" *) 5'h1a;
  assign swizz_minus_cnt_ring = \$8 [5] ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:90" *) \$9 [4:0] : \$8 [4:0];
  assign \$10  = load_start | (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:122" *) load_ring;
  assign left_out = \$10  ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:122" *) right_in : swizz_minus_cnt_ring;
  assign \s$18  = left_in + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:72" *) cnt_ring_combined;
  assign \$12  = \s$18 [4:0] >= (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:73" *) 5'h1a;
  assign \s_ge_26$20  = \$11  | (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:73" *) \$12 ;
  assign \$13  = \s$18  - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:74" *) 5'h1a;
  assign left_ptr = \s_ge_26$20  ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:75" *) \$13 [4:0] : \s$18 [4:0];
  assign \$15  = \$14  - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:87" *) cnt_ring_combined;
  assign \$16  = \$15 [5:0] + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:88" *) 5'h1a;
  assign swizz_l_minus_cnt_ring = \$15 [5] ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:90" *) \$16 [4:0] : \$15 [4:0];
  assign \$17  = cnt == (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:45" *) 5'h19;
  assign \$18  = cnt + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:48" *) 1'h1;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:21" *)
  always @(posedge clk)
    cnt <= \$19 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:24" *)
  always @(posedge clk)
    ring_setting <= \$20 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$4 ) begin end
    rtol_swizzle = 5'h00;
    casez (right_ptr)
      5'h00:
          rtol_swizzle = 5'h00;
      5'h01:
          rtol_swizzle = 5'h09;
      5'h02:
          rtol_swizzle = 5'h03;
      5'h03:
          rtol_swizzle = 5'h0a;
      5'h04:
          rtol_swizzle = 5'h12;
      5'h05:
          rtol_swizzle = 5'h08;
      5'h06:
          rtol_swizzle = 5'h11;
      5'h07:
          rtol_swizzle = 5'h14;
      5'h08:
          rtol_swizzle = 5'h17;
      5'h09:
          rtol_swizzle = 5'h01;
      5'h0a:
          rtol_swizzle = 5'h0b;
      5'h0b:
          rtol_swizzle = 5'h07;
      5'h0c:
          rtol_swizzle = 5'h16;
      5'h0d:
          rtol_swizzle = 5'h13;
      5'h0e:
          rtol_swizzle = 5'h0c;
      5'h0f:
          rtol_swizzle = 5'h02;
      5'h10:
          rtol_swizzle = 5'h10;
      5'h11:
          rtol_swizzle = 5'h06;
      5'h12:
          rtol_swizzle = 5'h19;
      5'h13:
          rtol_swizzle = 5'h0d;
      5'h14:
          rtol_swizzle = 5'h0f;
      5'h15:
          rtol_swizzle = 5'h18;
      5'h16:
          rtol_swizzle = 5'h05;
      5'h17:
          rtol_swizzle = 5'h15;
      5'h18:
          rtol_swizzle = 5'h0e;
      5'h19:
          rtol_swizzle = 5'h04;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$4 ) begin end
    \$14  = 5'h00;
    casez (left_ptr)
      5'h00:
          \$14  = 5'h00;
      5'h01:
          \$14  = 5'h09;
      5'h02:
          \$14  = 5'h0f;
      5'h03:
          \$14  = 5'h02;
      5'h04:
          \$14  = 5'h19;
      5'h05:
          \$14  = 5'h16;
      5'h06:
          \$14  = 5'h11;
      5'h07:
          \$14  = 5'h0b;
      5'h08:
          \$14  = 5'h05;
      5'h09:
          \$14  = 5'h01;
      5'h0a:
          \$14  = 5'h03;
      5'h0b:
          \$14  = 5'h0a;
      5'h0c:
          \$14  = 5'h0e;
      5'h0d:
          \$14  = 5'h13;
      5'h0e:
          \$14  = 5'h18;
      5'h0f:
          \$14  = 5'h14;
      5'h10:
          \$14  = 5'h10;
      5'h11:
          \$14  = 5'h06;
      5'h12:
          \$14  = 5'h04;
      5'h13:
          \$14  = 5'h0d;
      5'h14:
          \$14  = 5'h07;
      5'h15:
          \$14  = 5'h17;
      5'h16:
          \$14  = 5'h0c;
      5'h17:
          \$14  = 5'h08;
      5'h18:
          \$14  = 5'h15;
      5'h19:
          \$14  = 5'h12;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$4 ) begin end
    (* full_case = 32'd1 *)
    if (\$1 ) begin
      cnt_ring_combined = \$3 [4:0];
    end else begin
      cnt_ring_combined = \$4 [4:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$4 ) begin end
    \$19  = cnt;
    if (en) begin
      if (load_start) begin
        \$19  = right_in;
      end else if (load_ring) begin
      end else if (inc) begin
        (* full_case = 32'd1 *)
        if (\$17 ) begin
          \$19  = 5'h00;
        end else begin
          \$19  = \$18 [4:0];
        end
      end
    end
    if (rst) begin
      \$19  = 5'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$4 ) begin end
    \$20  = ring_setting;
    if (en) begin
      if (load_start) begin
      end else if (load_ring) begin
        \$20  = right_in;
      end
    end
    if (rst) begin
      \$20  = 5'h00;
    end
  end
  assign s_m_26 = \$7 [5:0];
  assign a_ext = { 1'h0, rtol_swizzle };
  assign b_ext = { 1'h0, cnt_ring_combined };
  assign \s$12  = \$8 [5:0];
  assign diff_plus_26 = \$9 [5:0];
  assign \s_m_26$21  = \$13 [5:0];
  assign \a_ext$23  = { 1'h0, \$14  };
  assign \b_ext$24  = { 1'h0, cnt_ring_combined };
  assign \s$25  = \$15 [5:0];
  assign \diff_plus_26$26  = \$16 [5:0];
  assign right_out = swizz_l_minus_cnt_ring;
  assign \$5  = s[5];
  assign \$11  = \s$18 [5];
endmodule

(* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:31" *)
(* generator = "Amaranth" *)
module \top.r2 (rst, right_in, is_at_turnover, left_out, swizz_l_minus_cnt_ring, left_in, en, load_start, load_ring, inc, clk);
  reg \$auto$verilog_backend.cc:2352:dump_module$5  = 0;
  wire \$1 ;
  wire \$10 ;
  wire \$11 ;
  wire \$12 ;
  wire [6:0] \$13 ;
  reg [4:0] \$14 ;
  wire [6:0] \$15 ;
  wire [6:0] \$16 ;
  wire \$17 ;
  wire [5:0] \$18 ;
  reg [4:0] \$19 ;
  wire [5:0] \$2 ;
  reg [4:0] \$20 ;
  wire [6:0] \$3 ;
  wire [5:0] \$4 ;
  wire \$5 ;
  wire \$6 ;
  wire [6:0] \$7 ;
  wire [6:0] \$8 ;
  wire [6:0] \$9 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:80" *)
  wire [5:0] a_ext;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:80" *)
  wire [5:0] \a_ext$23 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:81" *)
  wire [5:0] b_ext;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:81" *)
  wire [5:0] \b_ext$24 ;
  (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_ir.py:215" *)
  input clk;
  wire clk;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:21" *)
  reg [4:0] cnt = 5'h00;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:33" *)
  reg [4:0] cnt_ring_combined;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:82" *)
  wire [5:0] diff_plus_26;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:82" *)
  wire [5:0] \diff_plus_26$26 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:14" *)
  input en;
  wire en;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:17" *)
  input inc;
  wire inc;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:13" *)
  output is_at_turnover;
  wire is_at_turnover;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:10" *)
  input [4:0] left_in;
  wire [4:0] left_in;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:8" *)
  output [4:0] left_out;
  wire [4:0] left_out;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:27" *)
  wire [4:0] left_ptr;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:16" *)
  input load_ring;
  wire load_ring;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:15" *)
  input load_start;
  wire load_start;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:7" *)
  input [4:0] right_in;
  wire [4:0] right_in;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:11" *)
  wire [4:0] right_out;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:22" *)
  wire [4:0] right_ptr;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:24" *)
  reg [4:0] ring_setting = 5'h00;
  (* src = "/Users/virantha/dev/tinytapeout/ttsetup/env/lib/python3.12/site-packages/amaranth/hdl/_ir.py:215" *)
  input rst;
  wire rst;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:23" *)
  reg [4:0] rtol_swizzle;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:68" *)
  wire [5:0] s;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:79" *)
  wire [5:0] \s$12 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:68" *)
  wire [5:0] \s$18 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:79" *)
  wire [5:0] \s$25 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:70" *)
  wire s_ge_26;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:70" *)
  wire \s_ge_26$20 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:69" *)
  wire [5:0] s_m_26;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:69" *)
  wire [5:0] \s_m_26$21 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:11" *)
  output [4:0] swizz_l_minus_cnt_ring;
  wire [4:0] swizz_l_minus_cnt_ring;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:119" *)
  wire [4:0] swizz_minus_cnt_ring;
  assign \$1  = ring_setting > (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:34" *) cnt;
  assign \$2  = ring_setting - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:35" *) cnt;
  assign \$3  = $signed(6'h1a) - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:35" *) $signed(\$2 );
  assign \$4  = cnt - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:37" *) ring_setting;
  assign is_at_turnover = cnt == (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:61" *) 5'h15;
  assign s = right_in + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:72" *) cnt_ring_combined;
  assign \$6  = s[4:0] >= (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:73" *) 5'h1a;
  assign s_ge_26 = \$5  | (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:73" *) \$6 ;
  assign \$7  = s - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:74" *) 5'h1a;
  assign right_ptr = s_ge_26 ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:75" *) \$7 [4:0] : s[4:0];
  assign \$8  = rtol_swizzle - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:87" *) cnt_ring_combined;
  assign \$9  = \$8 [5:0] + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:88" *) 5'h1a;
  assign swizz_minus_cnt_ring = \$8 [5] ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:90" *) \$9 [4:0] : \$8 [4:0];
  assign \$10  = load_start | (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:122" *) load_ring;
  assign left_out = \$10  ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:122" *) right_in : swizz_minus_cnt_ring;
  assign \s$18  = left_in + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:72" *) cnt_ring_combined;
  assign \$12  = \s$18 [4:0] >= (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:73" *) 5'h1a;
  assign \s_ge_26$20  = \$11  | (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:73" *) \$12 ;
  assign \$13  = \s$18  - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:74" *) 5'h1a;
  assign left_ptr = \s_ge_26$20  ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:75" *) \$13 [4:0] : \s$18 [4:0];
  assign \$15  = \$14  - (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:87" *) cnt_ring_combined;
  assign \$16  = \$15 [5:0] + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:88" *) 5'h1a;
  assign swizz_l_minus_cnt_ring = \$15 [5] ? (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:90" *) \$16 [4:0] : \$15 [4:0];
  assign \$17  = cnt == (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:45" *) 5'h19;
  assign \$18  = cnt + (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:48" *) 1'h1;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:21" *)
  always @(posedge clk)
    cnt <= \$19 ;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:24" *)
  always @(posedge clk)
    ring_setting <= \$20 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$5 ) begin end
    rtol_swizzle = 5'h00;
    casez (right_ptr)
      5'h00:
          rtol_swizzle = 5'h01;
      5'h01:
          rtol_swizzle = 5'h03;
      5'h02:
          rtol_swizzle = 5'h05;
      5'h03:
          rtol_swizzle = 5'h07;
      5'h04:
          rtol_swizzle = 5'h09;
      5'h05:
          rtol_swizzle = 5'h0b;
      5'h06:
          rtol_swizzle = 5'h02;
      5'h07:
          rtol_swizzle = 5'h0f;
      5'h08:
          rtol_swizzle = 5'h11;
      5'h09:
          rtol_swizzle = 5'h13;
      5'h0a:
          rtol_swizzle = 5'h17;
      5'h0b:
          rtol_swizzle = 5'h15;
      5'h0c:
          rtol_swizzle = 5'h19;
      5'h0d:
          rtol_swizzle = 5'h0d;
      5'h0e:
          rtol_swizzle = 5'h18;
      5'h0f:
          rtol_swizzle = 5'h04;
      5'h10:
          rtol_swizzle = 5'h08;
      5'h11:
          rtol_swizzle = 5'h16;
      5'h12:
          rtol_swizzle = 5'h06;
      5'h13:
          rtol_swizzle = 5'h00;
      5'h14:
          rtol_swizzle = 5'h0a;
      5'h15:
          rtol_swizzle = 5'h0c;
      5'h16:
          rtol_swizzle = 5'h14;
      5'h17:
          rtol_swizzle = 5'h12;
      5'h18:
          rtol_swizzle = 5'h10;
      5'h19:
          rtol_swizzle = 5'h0e;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$5 ) begin end
    \$14  = 5'h00;
    casez (left_ptr)
      5'h00:
          \$14  = 5'h13;
      5'h01:
          \$14  = 5'h00;
      5'h02:
          \$14  = 5'h06;
      5'h03:
          \$14  = 5'h01;
      5'h04:
          \$14  = 5'h0f;
      5'h05:
          \$14  = 5'h02;
      5'h06:
          \$14  = 5'h12;
      5'h07:
          \$14  = 5'h03;
      5'h08:
          \$14  = 5'h10;
      5'h09:
          \$14  = 5'h04;
      5'h0a:
          \$14  = 5'h14;
      5'h0b:
          \$14  = 5'h05;
      5'h0c:
          \$14  = 5'h15;
      5'h0d:
          \$14  = 5'h0d;
      5'h0e:
          \$14  = 5'h19;
      5'h0f:
          \$14  = 5'h07;
      5'h10:
          \$14  = 5'h18;
      5'h11:
          \$14  = 5'h08;
      5'h12:
          \$14  = 5'h17;
      5'h13:
          \$14  = 5'h09;
      5'h14:
          \$14  = 5'h16;
      5'h15:
          \$14  = 5'h0b;
      5'h16:
          \$14  = 5'h11;
      5'h17:
          \$14  = 5'h0a;
      5'h18:
          \$14  = 5'h0e;
      5'h19:
          \$14  = 5'h0c;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$5 ) begin end
    (* full_case = 32'd1 *)
    if (\$1 ) begin
      cnt_ring_combined = \$3 [4:0];
    end else begin
      cnt_ring_combined = \$4 [4:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$5 ) begin end
    \$19  = cnt;
    if (en) begin
      if (load_start) begin
        \$19  = right_in;
      end else if (load_ring) begin
      end else if (inc) begin
        (* full_case = 32'd1 *)
        if (\$17 ) begin
          \$19  = 5'h00;
        end else begin
          \$19  = \$18 [4:0];
        end
      end
    end
    if (rst) begin
      \$19  = 5'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$5 ) begin end
    \$20  = ring_setting;
    if (en) begin
      if (load_start) begin
      end else if (load_ring) begin
        \$20  = right_in;
      end
    end
    if (rst) begin
      \$20  = 5'h00;
    end
  end
  assign s_m_26 = \$7 [5:0];
  assign a_ext = { 1'h0, rtol_swizzle };
  assign b_ext = { 1'h0, cnt_ring_combined };
  assign \s$12  = \$8 [5:0];
  assign diff_plus_26 = \$9 [5:0];
  assign \s_m_26$21  = \$13 [5:0];
  assign \a_ext$23  = { 1'h0, \$14  };
  assign \b_ext$24  = { 1'h0, cnt_ring_combined };
  assign \s$25  = \$15 [5:0];
  assign \diff_plus_26$26  = \$16 [5:0];
  assign right_out = swizz_l_minus_cnt_ring;
  assign \$5  = s[5];
  assign \$11  = \s$18 [5];
endmodule

(* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:163" *)
(* generator = "Amaranth" *)
module \top.ref (left_out, right_ptr);
  reg \$auto$verilog_backend.cc:2352:dump_module$6  = 0;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:21" *)
  wire [4:0] cnt;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:13" *)
  wire is_at_turnover;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:8" *)
  output [4:0] left_out;
  reg [4:0] left_out;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:27" *)
  wire [4:0] left_ptr;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:7" *)
  wire [4:0] right_in;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:11" *)
  wire [4:0] right_out;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:7" *)
  input [4:0] right_ptr;
  wire [4:0] right_ptr;
  (* src = "/Users/virantha/dev/tinytapeout/tt10-enigma/src/rotor.py:23" *)
  wire [4:0] rtol_swizzle;
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$6 ) begin end
    left_out = 5'h00;
    casez (right_ptr)
      5'h00:
          left_out = 5'h18;
      5'h01:
          left_out = 5'h11;
      5'h02:
          left_out = 5'h14;
      5'h03:
          left_out = 5'h07;
      5'h04:
          left_out = 5'h10;
      5'h05:
          left_out = 5'h12;
      5'h06:
          left_out = 5'h0b;
      5'h07:
          left_out = 5'h03;
      5'h08:
          left_out = 5'h0f;
      5'h09:
          left_out = 5'h17;
      5'h0a:
          left_out = 5'h0d;
      5'h0b:
          left_out = 5'h06;
      5'h0c:
          left_out = 5'h0e;
      5'h0d:
          left_out = 5'h0a;
      5'h0e:
          left_out = 5'h0c;
      5'h0f:
          left_out = 5'h08;
      5'h10:
          left_out = 5'h04;
      5'h11:
          left_out = 5'h01;
      5'h12:
          left_out = 5'h05;
      5'h13:
          left_out = 5'h19;
      5'h14:
          left_out = 5'h02;
      5'h15:
          left_out = 5'h16;
      5'h16:
          left_out = 5'h15;
      5'h17:
          left_out = 5'h09;
      5'h18:
          left_out = 5'h00;
      5'h19:
          left_out = 5'h13;
    endcase
  end
  assign right_in = right_ptr;
  assign right_out = 5'h00;
  assign is_at_turnover = 1'h0;
  assign rtol_swizzle = 5'h00;
  assign cnt = 5'h00;
  assign left_ptr = 5'h00;
endmodule
